site_name: GTProto
nav:
  - Home: index.md
  - Basic usage: basics.md
  - Authentication: auth.md
  - State: state.md
  - Messaging: messaging.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
theme: readthedocs
plugins:
  - include-markdown
