// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: board_members.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoardMembersListResponse_Error int32

const (
	// Reserved
	BoardMembersListResponse_UNKNOWN_ERROR BoardMembersListResponse_Error = 0
	// Invalid chat ID
	BoardMembersListResponse_INVALID_CHAT_ERROR BoardMembersListResponse_Error = 1
	// Access to chat is denied
	BoardMembersListResponse_ACCESS_DENIED_ERROR BoardMembersListResponse_Error = 2
	// Invalid limit
	BoardMembersListResponse_INVALID_LIMIT_ERROR BoardMembersListResponse_Error = 3
)

// Enum value maps for BoardMembersListResponse_Error.
var (
	BoardMembersListResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
		3: "INVALID_LIMIT_ERROR",
	}
	BoardMembersListResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
		"INVALID_LIMIT_ERROR": 3,
	}
)

func (x BoardMembersListResponse_Error) Enum() *BoardMembersListResponse_Error {
	p := new(BoardMembersListResponse_Error)
	*p = x
	return p
}

func (x BoardMembersListResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardMembersListResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_board_members_proto_enumTypes[0].Descriptor()
}

func (BoardMembersListResponse_Error) Type() protoreflect.EnumType {
	return &file_board_members_proto_enumTypes[0]
}

func (x BoardMembersListResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardMembersListResponse_Error.Descriptor instead.
func (BoardMembersListResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{1, 0}
}

type CreateOrUpdateBoardMembersResponse_Error int32

const (
	// Reserved
	CreateOrUpdateBoardMembersResponse_UNKNOWN_ERROR CreateOrUpdateBoardMembersResponse_Error = 0
	// Invalid chat ID
	CreateOrUpdateBoardMembersResponse_INVALID_CHAT_ERROR CreateOrUpdateBoardMembersResponse_Error = 1
	// Access to chat is denied
	CreateOrUpdateBoardMembersResponse_ACCESS_DENIED_ERROR CreateOrUpdateBoardMembersResponse_Error = 2
)

// Enum value maps for CreateOrUpdateBoardMembersResponse_Error.
var (
	CreateOrUpdateBoardMembersResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
	}
	CreateOrUpdateBoardMembersResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
	}
)

func (x CreateOrUpdateBoardMembersResponse_Error) Enum() *CreateOrUpdateBoardMembersResponse_Error {
	p := new(CreateOrUpdateBoardMembersResponse_Error)
	*p = x
	return p
}

func (x CreateOrUpdateBoardMembersResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrUpdateBoardMembersResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_board_members_proto_enumTypes[1].Descriptor()
}

func (CreateOrUpdateBoardMembersResponse_Error) Type() protoreflect.EnumType {
	return &file_board_members_proto_enumTypes[1]
}

func (x CreateOrUpdateBoardMembersResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrUpdateBoardMembersResponse_Error.Descriptor instead.
func (CreateOrUpdateBoardMembersResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{3, 0}
}

type RemoveBoardMembersResponse_Error int32

const (
	// Reserved
	RemoveBoardMembersResponse_UNKNOWN_ERROR RemoveBoardMembersResponse_Error = 0
	// Invalid chat ID
	RemoveBoardMembersResponse_INVALID_CHAT_ERROR RemoveBoardMembersResponse_Error = 1
	// Access to chat is denied
	RemoveBoardMembersResponse_ACCESS_DENIED_ERROR RemoveBoardMembersResponse_Error = 2
)

// Enum value maps for RemoveBoardMembersResponse_Error.
var (
	RemoveBoardMembersResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
	}
	RemoveBoardMembersResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
	}
)

func (x RemoveBoardMembersResponse_Error) Enum() *RemoveBoardMembersResponse_Error {
	p := new(RemoveBoardMembersResponse_Error)
	*p = x
	return p
}

func (x RemoveBoardMembersResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveBoardMembersResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_board_members_proto_enumTypes[2].Descriptor()
}

func (RemoveBoardMembersResponse_Error) Type() protoreflect.EnumType {
	return &file_board_members_proto_enumTypes[2]
}

func (x RemoveBoardMembersResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveBoardMembersResponse_Error.Descriptor instead.
func (RemoveBoardMembersResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{5, 0}
}

type BoardMembersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Chat ID
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Pagination limit. Default: StateResponse.max_results_on_page
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset. Default: 0
	Offset uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// User ID. If not set, returns all members. If "me", returns current user.
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *BoardMembersListRequest) Reset() {
	*x = BoardMembersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_members_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardMembersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMembersListRequest) ProtoMessage() {}

func (x *BoardMembersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_members_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMembersListRequest.ProtoReflect.Descriptor instead.
func (*BoardMembersListRequest) Descriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{0}
}

func (x *BoardMembersListRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *BoardMembersListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BoardMembersListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BoardMembersListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BoardMembersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Errors
	Errors []BoardMembersListResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.BoardMembersListResponse_Error" json:"errors,omitempty"`
	// Board members list
	Members []*BoardMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *BoardMembersListResponse) Reset() {
	*x = BoardMembersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_members_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardMembersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMembersListResponse) ProtoMessage() {}

func (x *BoardMembersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_members_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMembersListResponse.ProtoReflect.Descriptor instead.
func (*BoardMembersListResponse) Descriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{1}
}

func (x *BoardMembersListResponse) GetErrors() []BoardMembersListResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BoardMembersListResponse) GetMembers() []*BoardMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateOrUpdateBoardMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Chat ID
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Board members update request
	Members []*BoardMemberUpdate `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *CreateOrUpdateBoardMembersRequest) Reset() {
	*x = CreateOrUpdateBoardMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_members_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateBoardMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateBoardMembersRequest) ProtoMessage() {}

func (x *CreateOrUpdateBoardMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_members_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateBoardMembersRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateBoardMembersRequest) Descriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrUpdateBoardMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateOrUpdateBoardMembersRequest) GetMembers() []*BoardMemberUpdate {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateOrUpdateBoardMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Errors
	Errors []CreateOrUpdateBoardMembersResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.CreateOrUpdateBoardMembersResponse_Error" json:"errors,omitempty"`
	// Board members list
	NewOrUpdatedMembers []*BoardMember `protobuf:"bytes,2,rep,name=new_or_updated_members,json=newOrUpdatedMembers,proto3" json:"new_or_updated_members,omitempty"`
	// Board chat information
	Chat *Chat `protobuf:"bytes,3,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *CreateOrUpdateBoardMembersResponse) Reset() {
	*x = CreateOrUpdateBoardMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_members_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateBoardMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateBoardMembersResponse) ProtoMessage() {}

func (x *CreateOrUpdateBoardMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_members_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateBoardMembersResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateBoardMembersResponse) Descriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrUpdateBoardMembersResponse) GetErrors() []CreateOrUpdateBoardMembersResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CreateOrUpdateBoardMembersResponse) GetNewOrUpdatedMembers() []*BoardMember {
	if x != nil {
		return x.NewOrUpdatedMembers
	}
	return nil
}

func (x *CreateOrUpdateBoardMembersResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type RemoveBoardMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Chat ID
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// User IDs. UUID or "me"
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *RemoveBoardMembersRequest) Reset() {
	*x = RemoveBoardMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_members_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBoardMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBoardMembersRequest) ProtoMessage() {}

func (x *RemoveBoardMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_members_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBoardMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveBoardMembersRequest) Descriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveBoardMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveBoardMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveBoardMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Errors
	Errors []RemoveBoardMembersResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.RemoveBoardMembersResponse_Error" json:"errors,omitempty"`
	// Board chat information
	Chat *Chat `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *RemoveBoardMembersResponse) Reset() {
	*x = RemoveBoardMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_members_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBoardMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBoardMembersResponse) ProtoMessage() {}

func (x *RemoveBoardMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_members_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBoardMembersResponse.ProtoReflect.Descriptor instead.
func (*RemoveBoardMembersResponse) Descriptor() ([]byte, []int) {
	return file_board_members_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveBoardMembersResponse) GetErrors() []RemoveBoardMembersResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *RemoveBoardMembersResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

var File_board_members_proto protoreflect.FileDescriptor

var file_board_members_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x74, 0x63, 0x68, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79,
	0x0a, 0x17, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xf3, 0x01, 0x0a, 0x18, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x64, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x22,
	0x73, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x35, 0x0a,
	0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0xad, 0x02, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x74, 0x65,
	0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x4a, 0x0a, 0x16, 0x6e, 0x65, 0x77, 0x5f, 0x6f,
	0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x13,
	0x6e, 0x65, 0x77, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x4b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43,
	0x48, 0x41, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x22, 0x4f, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x4b, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45,
	0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_board_members_proto_rawDescOnce sync.Once
	file_board_members_proto_rawDescData = file_board_members_proto_rawDesc
)

func file_board_members_proto_rawDescGZIP() []byte {
	file_board_members_proto_rawDescOnce.Do(func() {
		file_board_members_proto_rawDescData = protoimpl.X.CompressGZIP(file_board_members_proto_rawDescData)
	})
	return file_board_members_proto_rawDescData
}

var file_board_members_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_board_members_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_board_members_proto_goTypes = []interface{}{
	(BoardMembersListResponse_Error)(0),           // 0: teaproto.BoardMembersListResponse.Error
	(CreateOrUpdateBoardMembersResponse_Error)(0), // 1: teaproto.CreateOrUpdateBoardMembersResponse.Error
	(RemoveBoardMembersResponse_Error)(0),         // 2: teaproto.RemoveBoardMembersResponse.Error
	(*BoardMembersListRequest)(nil),               // 3: teaproto.BoardMembersListRequest
	(*BoardMembersListResponse)(nil),              // 4: teaproto.BoardMembersListResponse
	(*CreateOrUpdateBoardMembersRequest)(nil),     // 5: teaproto.CreateOrUpdateBoardMembersRequest
	(*CreateOrUpdateBoardMembersResponse)(nil),    // 6: teaproto.CreateOrUpdateBoardMembersResponse
	(*RemoveBoardMembersRequest)(nil),             // 7: teaproto.RemoveBoardMembersRequest
	(*RemoveBoardMembersResponse)(nil),            // 8: teaproto.RemoveBoardMembersResponse
	(*BoardMember)(nil),                           // 9: teatypes.BoardMember
	(*BoardMemberUpdate)(nil),                     // 10: teatypes.BoardMemberUpdate
	(*Chat)(nil),                                  // 11: teatypes.Chat
}
var file_board_members_proto_depIdxs = []int32{
	0,  // 0: teaproto.BoardMembersListResponse.errors:type_name -> teaproto.BoardMembersListResponse.Error
	9,  // 1: teaproto.BoardMembersListResponse.members:type_name -> teatypes.BoardMember
	10, // 2: teaproto.CreateOrUpdateBoardMembersRequest.members:type_name -> teatypes.BoardMemberUpdate
	1,  // 3: teaproto.CreateOrUpdateBoardMembersResponse.errors:type_name -> teaproto.CreateOrUpdateBoardMembersResponse.Error
	9,  // 4: teaproto.CreateOrUpdateBoardMembersResponse.new_or_updated_members:type_name -> teatypes.BoardMember
	11, // 5: teaproto.CreateOrUpdateBoardMembersResponse.chat:type_name -> teatypes.Chat
	2,  // 6: teaproto.RemoveBoardMembersResponse.errors:type_name -> teaproto.RemoveBoardMembersResponse.Error
	11, // 7: teaproto.RemoveBoardMembersResponse.chat:type_name -> teatypes.Chat
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_board_members_proto_init() }
func file_board_members_proto_init() {
	if File_board_members_proto != nil {
		return
	}
	file_teatypes_tboards_proto_init()
	file_teatypes_tchats_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_board_members_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardMembersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_members_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardMembersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_members_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateBoardMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_members_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateBoardMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_members_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBoardMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_members_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBoardMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_board_members_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_board_members_proto_goTypes,
		DependencyIndexes: file_board_members_proto_depIdxs,
		EnumInfos:         file_board_members_proto_enumTypes,
		MessageInfos:      file_board_members_proto_msgTypes,
	}.Build()
	File_board_members_proto = out.File
	file_board_members_proto_rawDesc = nil
	file_board_members_proto_goTypes = nil
	file_board_members_proto_depIdxs = nil
}
