// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.24.3
// source: core_boards.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Board is a collection of task chats (for now. In future it can be a collection of any chats)
type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Icon       *Icon  `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	NumMembers uint32 `protobuf:"varint,3,opt,name=num_members,json=numMembers,proto3" json:"num_members,omitempty"` // read only computed field
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_boards_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_core_boards_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_core_boards_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Board) GetIcon() *Icon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Board) GetNumMembers() uint32 {
	if x != nil {
		return x.NumMembers
	}
	return 0
}

// Roles are predefined on server side. In future we can add custom roles via API.
type BoardRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                    // value is unique inside board
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                               // human readable title
	CanAddNewMembers     bool     `protobuf:"varint,11,opt,name=can_add_new_members,json=canAddNewMembers,proto3" json:"can_add_new_members,omitempty"`           // can add new members to board or task
	CanChangeInformation bool     `protobuf:"varint,12,opt,name=can_change_information,json=canChangeInformation,proto3" json:"can_change_information,omitempty"` // title, icon
	CanSetRoleIds        []uint32 `protobuf:"varint,13,rep,packed,name=can_set_role_ids,json=canSetRoleIds,proto3" json:"can_set_role_ids,omitempty"`
	CanCreateTasks       bool     `protobuf:"varint,15,opt,name=can_create_tasks,json=canCreateTasks,proto3" json:"can_create_tasks,omitempty"`
}

func (x *BoardRole) Reset() {
	*x = BoardRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_boards_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardRole) ProtoMessage() {}

func (x *BoardRole) ProtoReflect() protoreflect.Message {
	mi := &file_core_boards_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardRole.ProtoReflect.Descriptor instead.
func (*BoardRole) Descriptor() ([]byte, []int) {
	return file_core_boards_proto_rawDescGZIP(), []int{1}
}

func (x *BoardRole) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BoardRole) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BoardRole) GetCanAddNewMembers() bool {
	if x != nil {
		return x.CanAddNewMembers
	}
	return false
}

func (x *BoardRole) GetCanChangeInformation() bool {
	if x != nil {
		return x.CanChangeInformation
	}
	return false
}

func (x *BoardRole) GetCanSetRoleIds() []uint32 {
	if x != nil {
		return x.CanSetRoleIds
	}
	return nil
}

func (x *BoardRole) GetCanCreateTasks() bool {
	if x != nil {
		return x.CanCreateTasks
	}
	return false
}

type BoardMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User                 *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	BoardRoleId          uint32 `protobuf:"varint,6,opt,name=board_role_id,json=boardRoleId,proto3" json:"board_role_id,omitempty"`
	CanIRemoveThisMember bool   `protobuf:"varint,5,opt,name=can_i_remove_this_member,json=canIRemoveThisMember,proto3" json:"can_i_remove_this_member,omitempty"`
}

func (x *BoardMember) Reset() {
	*x = BoardMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_boards_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMember) ProtoMessage() {}

func (x *BoardMember) ProtoReflect() protoreflect.Message {
	mi := &file_core_boards_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMember.ProtoReflect.Descriptor instead.
func (*BoardMember) Descriptor() ([]byte, []int) {
	return file_core_boards_proto_rawDescGZIP(), []int{2}
}

func (x *BoardMember) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BoardMember) GetBoardRoleId() uint32 {
	if x != nil {
		return x.BoardRoleId
	}
	return 0
}

func (x *BoardMember) GetCanIRemoveThisMember() bool {
	if x != nil {
		return x.CanIRemoveThisMember
	}
	return false
}

type BoardMemberUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // uuid or "me"
	BoardRoleId uint32 `protobuf:"varint,2,opt,name=board_role_id,json=boardRoleId,proto3" json:"board_role_id,omitempty"` // 0 = default role
}

func (x *BoardMemberUpdate) Reset() {
	*x = BoardMemberUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_boards_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardMemberUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMemberUpdate) ProtoMessage() {}

func (x *BoardMemberUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_core_boards_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMemberUpdate.ProtoReflect.Descriptor instead.
func (*BoardMemberUpdate) Descriptor() ([]byte, []int) {
	return file_core_boards_proto_rawDescGZIP(), []int{3}
}

func (x *BoardMemberUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BoardMemberUpdate) GetBoardRoleId() uint32 {
	if x != nil {
		return x.BoardRoleId
	}
	return 0
}

var File_core_boards_proto protoreflect.FileDescriptor

var file_core_boards_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x62, 0x0a, 0x05, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x52,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x09, 0x42, 0x6f, 0x61, 0x72, 0x64,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x13, 0x63, 0x61,
	0x6e, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x63, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x4e,
	0x65, 0x77, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x61, 0x6e,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x63, 0x61, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x10, 0x63, 0x61, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x61, 0x6e, 0x53, 0x65,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x61, 0x6e, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x63, 0x61, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x18, 0x63, 0x61,
	0x6e, 0x5f, 0x69, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x74, 0x68, 0x69, 0x73, 0x5f,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x63, 0x61,
	0x6e, 0x49, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x68, 0x69, 0x73, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x50, 0x0a, 0x11, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_boards_proto_rawDescOnce sync.Once
	file_core_boards_proto_rawDescData = file_core_boards_proto_rawDesc
)

func file_core_boards_proto_rawDescGZIP() []byte {
	file_core_boards_proto_rawDescOnce.Do(func() {
		file_core_boards_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_boards_proto_rawDescData)
	})
	return file_core_boards_proto_rawDescData
}

var file_core_boards_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_boards_proto_goTypes = []interface{}{
	(*Board)(nil),             // 0: teaproto.Board
	(*BoardRole)(nil),         // 1: teaproto.BoardRole
	(*BoardMember)(nil),       // 2: teaproto.BoardMember
	(*BoardMemberUpdate)(nil), // 3: teaproto.BoardMemberUpdate
	(*Icon)(nil),              // 4: teaproto.Icon
	(*User)(nil),              // 5: teaproto.User
}
var file_core_boards_proto_depIdxs = []int32{
	4, // 0: teaproto.Board.icon:type_name -> teaproto.Icon
	5, // 1: teaproto.BoardMember.user:type_name -> teaproto.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_boards_proto_init() }
func file_core_boards_proto_init() {
	if File_core_boards_proto != nil {
		return
	}
	file_core_users_proto_init()
	file_core_images_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_core_boards_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_boards_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_boards_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_boards_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardMemberUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_boards_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_boards_proto_goTypes,
		DependencyIndexes: file_core_boards_proto_depIdxs,
		MessageInfos:      file_core_boards_proto_msgTypes,
	}.Build()
	File_core_boards_proto = out.File
	file_core_boards_proto_rawDesc = nil
	file_core_boards_proto_goTypes = nil
	file_core_boards_proto_depIdxs = nil
}
