// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: group_members.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMembersListResponse_Error int32

const (
	GroupMembersListResponse_UNKNOWN_ERROR       GroupMembersListResponse_Error = 0
	GroupMembersListResponse_INVALID_CHAT_ERROR  GroupMembersListResponse_Error = 1
	GroupMembersListResponse_INVALID_LIMIT_ERROR GroupMembersListResponse_Error = 2
	GroupMembersListResponse_INVALID_USER_ERROR  GroupMembersListResponse_Error = 3
	GroupMembersListResponse_ACCESS_DENIED_ERROR GroupMembersListResponse_Error = 4
)

// Enum value maps for GroupMembersListResponse_Error.
var (
	GroupMembersListResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "INVALID_LIMIT_ERROR",
		3: "INVALID_USER_ERROR",
		4: "ACCESS_DENIED_ERROR",
	}
	GroupMembersListResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"INVALID_LIMIT_ERROR": 2,
		"INVALID_USER_ERROR":  3,
		"ACCESS_DENIED_ERROR": 4,
	}
)

func (x GroupMembersListResponse_Error) Enum() *GroupMembersListResponse_Error {
	p := new(GroupMembersListResponse_Error)
	*p = x
	return p
}

func (x GroupMembersListResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupMembersListResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_group_members_proto_enumTypes[0].Descriptor()
}

func (GroupMembersListResponse_Error) Type() protoreflect.EnumType {
	return &file_group_members_proto_enumTypes[0]
}

func (x GroupMembersListResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupMembersListResponse_Error.Descriptor instead.
func (GroupMembersListResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{1, 0}
}

type CreateGroupMembersResponse_Error int32

const (
	CreateGroupMembersResponse_UNKNOWN_ERROR       CreateGroupMembersResponse_Error = 0
	CreateGroupMembersResponse_INVALID_CHAT_ERROR  CreateGroupMembersResponse_Error = 1
	CreateGroupMembersResponse_ACCESS_DENIED_ERROR CreateGroupMembersResponse_Error = 2
)

// Enum value maps for CreateGroupMembersResponse_Error.
var (
	CreateGroupMembersResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
	}
	CreateGroupMembersResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
	}
)

func (x CreateGroupMembersResponse_Error) Enum() *CreateGroupMembersResponse_Error {
	p := new(CreateGroupMembersResponse_Error)
	*p = x
	return p
}

func (x CreateGroupMembersResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateGroupMembersResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_group_members_proto_enumTypes[1].Descriptor()
}

func (CreateGroupMembersResponse_Error) Type() protoreflect.EnumType {
	return &file_group_members_proto_enumTypes[1]
}

func (x CreateGroupMembersResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateGroupMembersResponse_Error.Descriptor instead.
func (CreateGroupMembersResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{3, 0}
}

type UpdateGroupMemberResponse_Error int32

const (
	UpdateGroupMemberResponse_UNKNOWN_ERROR       UpdateGroupMemberResponse_Error = 0
	UpdateGroupMemberResponse_INVALID_CHAT_ERROR  UpdateGroupMemberResponse_Error = 1
	UpdateGroupMemberResponse_INVALID_USER_ERROR  UpdateGroupMemberResponse_Error = 2
	UpdateGroupMemberResponse_ACCESS_DENIED_ERROR UpdateGroupMemberResponse_Error = 3
)

// Enum value maps for UpdateGroupMemberResponse_Error.
var (
	UpdateGroupMemberResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "INVALID_USER_ERROR",
		3: "ACCESS_DENIED_ERROR",
	}
	UpdateGroupMemberResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"INVALID_USER_ERROR":  2,
		"ACCESS_DENIED_ERROR": 3,
	}
)

func (x UpdateGroupMemberResponse_Error) Enum() *UpdateGroupMemberResponse_Error {
	p := new(UpdateGroupMemberResponse_Error)
	*p = x
	return p
}

func (x UpdateGroupMemberResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateGroupMemberResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_group_members_proto_enumTypes[2].Descriptor()
}

func (UpdateGroupMemberResponse_Error) Type() protoreflect.EnumType {
	return &file_group_members_proto_enumTypes[2]
}

func (x UpdateGroupMemberResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateGroupMemberResponse_Error.Descriptor instead.
func (UpdateGroupMemberResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{5, 0}
}

type RemoveGroupMemberResponse_Error int32

const (
	RemoveGroupMemberResponse_UNKNOWN_ERROR       RemoveGroupMemberResponse_Error = 0
	RemoveGroupMemberResponse_INVALID_CHAT_ERROR  RemoveGroupMemberResponse_Error = 1
	RemoveGroupMemberResponse_INVALID_USER_ERROR  RemoveGroupMemberResponse_Error = 2
	RemoveGroupMemberResponse_ACCESS_DENIED_ERROR RemoveGroupMemberResponse_Error = 3
)

// Enum value maps for RemoveGroupMemberResponse_Error.
var (
	RemoveGroupMemberResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "INVALID_USER_ERROR",
		3: "ACCESS_DENIED_ERROR",
	}
	RemoveGroupMemberResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"INVALID_USER_ERROR":  2,
		"ACCESS_DENIED_ERROR": 3,
	}
)

func (x RemoveGroupMemberResponse_Error) Enum() *RemoveGroupMemberResponse_Error {
	p := new(RemoveGroupMemberResponse_Error)
	*p = x
	return p
}

func (x RemoveGroupMemberResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveGroupMemberResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_group_members_proto_enumTypes[3].Descriptor()
}

func (RemoveGroupMemberResponse_Error) Type() protoreflect.EnumType {
	return &file_group_members_proto_enumTypes[3]
}

func (x RemoveGroupMemberResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveGroupMemberResponse_Error.Descriptor instead.
func (RemoveGroupMemberResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{7, 0}
}

type GroupMembersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // default: StateResponse.max_results_on_page
	Offset uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// filters
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid or "me"
}

func (x *GroupMembersListRequest) Reset() {
	*x = GroupMembersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMembersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersListRequest) ProtoMessage() {}

func (x *GroupMembersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersListRequest.ProtoReflect.Descriptor instead.
func (*GroupMembersListRequest) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMembersListRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GroupMembersListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GroupMembersListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GroupMembersListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GroupMembersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors  []GroupMembersListResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.GroupMembersListResponse_Error" json:"errors,omitempty"`
	Members []*GroupMember                   `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *GroupMembersListResponse) Reset() {
	*x = GroupMembersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMembersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersListResponse) ProtoMessage() {}

func (x *GroupMembersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersListResponse.ProtoReflect.Descriptor instead.
func (*GroupMembersListResponse) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMembersListResponse) GetErrors() []GroupMembersListResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GroupMembersListResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateGroupMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *CreateGroupMembersRequest) Reset() {
	*x = CreateGroupMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupMembersRequest) ProtoMessage() {}

func (x *CreateGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateGroupMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CreateGroupMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors  []CreateGroupMembersResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.CreateGroupMembersResponse_Error" json:"errors,omitempty"`
	Members []*GroupMember                     `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *CreateGroupMembersResponse) Reset() {
	*x = CreateGroupMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupMembersResponse) ProtoMessage() {}

func (x *CreateGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupMembersResponse) GetErrors() []CreateGroupMembersResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CreateGroupMembersResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateGroupMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId      string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid or "me"
	GroupRoleId uint32 `protobuf:"varint,3,opt,name=group_role_id,json=groupRoleId,proto3" json:"group_role_id,omitempty"`
}

func (x *UpdateGroupMemberRequest) Reset() {
	*x = UpdateGroupMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupMemberRequest) ProtoMessage() {}

func (x *UpdateGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateGroupMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateGroupMemberRequest) GetGroupRoleId() uint32 {
	if x != nil {
		return x.GroupRoleId
	}
	return 0
}

type UpdateGroupMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []UpdateGroupMemberResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.UpdateGroupMemberResponse_Error" json:"errors,omitempty"`
	Member *GroupMember                      `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *UpdateGroupMemberResponse) Reset() {
	*x = UpdateGroupMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupMemberResponse) ProtoMessage() {}

func (x *UpdateGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGroupMemberResponse) GetErrors() []UpdateGroupMemberResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *UpdateGroupMemberResponse) GetMember() *GroupMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveGroupMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid or "me"
}

func (x *RemoveGroupMemberRequest) Reset() {
	*x = RemoveGroupMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRequest) ProtoMessage() {}

func (x *RemoveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveGroupMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveGroupMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveGroupMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []RemoveGroupMemberResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.RemoveGroupMemberResponse_Error" json:"errors,omitempty"`
}

func (x *RemoveGroupMemberResponse) Reset() {
	*x = RemoveGroupMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_members_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberResponse) ProtoMessage() {}

func (x *RemoveGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_members_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_group_members_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveGroupMemberResponse) GetErrors() []RemoveGroupMemberResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_group_members_proto protoreflect.FileDescriptor

var file_group_members_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x17, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x8b, 0x02, 0x0a, 0x18, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x28, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x2f, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x22, 0x7c, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x16,
	0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12,
	0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04,
	0x22, 0x4f, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x22, 0xde, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x2a, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x4b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11,
	0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x41,
	0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x02, 0x22, 0x70, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0xf2, 0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0e, 0x32, 0x29, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a,
	0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x54,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45,
	0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x4c, 0x0a, 0x18, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc3, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x63, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44,
	0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_group_members_proto_rawDescOnce sync.Once
	file_group_members_proto_rawDescData = file_group_members_proto_rawDesc
)

func file_group_members_proto_rawDescGZIP() []byte {
	file_group_members_proto_rawDescOnce.Do(func() {
		file_group_members_proto_rawDescData = protoimpl.X.CompressGZIP(file_group_members_proto_rawDescData)
	})
	return file_group_members_proto_rawDescData
}

var file_group_members_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_group_members_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_group_members_proto_goTypes = []interface{}{
	(GroupMembersListResponse_Error)(0),   // 0: teaproto.GroupMembersListResponse.Error
	(CreateGroupMembersResponse_Error)(0), // 1: teaproto.CreateGroupMembersResponse.Error
	(UpdateGroupMemberResponse_Error)(0),  // 2: teaproto.UpdateGroupMemberResponse.Error
	(RemoveGroupMemberResponse_Error)(0),  // 3: teaproto.RemoveGroupMemberResponse.Error
	(*GroupMembersListRequest)(nil),       // 4: teaproto.GroupMembersListRequest
	(*GroupMembersListResponse)(nil),      // 5: teaproto.GroupMembersListResponse
	(*CreateGroupMembersRequest)(nil),     // 6: teaproto.CreateGroupMembersRequest
	(*CreateGroupMembersResponse)(nil),    // 7: teaproto.CreateGroupMembersResponse
	(*UpdateGroupMemberRequest)(nil),      // 8: teaproto.UpdateGroupMemberRequest
	(*UpdateGroupMemberResponse)(nil),     // 9: teaproto.UpdateGroupMemberResponse
	(*RemoveGroupMemberRequest)(nil),      // 10: teaproto.RemoveGroupMemberRequest
	(*RemoveGroupMemberResponse)(nil),     // 11: teaproto.RemoveGroupMemberResponse
	(*GroupMember)(nil),                   // 12: teatypes.GroupMember
}
var file_group_members_proto_depIdxs = []int32{
	0,  // 0: teaproto.GroupMembersListResponse.errors:type_name -> teaproto.GroupMembersListResponse.Error
	12, // 1: teaproto.GroupMembersListResponse.members:type_name -> teatypes.GroupMember
	1,  // 2: teaproto.CreateGroupMembersResponse.errors:type_name -> teaproto.CreateGroupMembersResponse.Error
	12, // 3: teaproto.CreateGroupMembersResponse.members:type_name -> teatypes.GroupMember
	2,  // 4: teaproto.UpdateGroupMemberResponse.errors:type_name -> teaproto.UpdateGroupMemberResponse.Error
	12, // 5: teaproto.UpdateGroupMemberResponse.member:type_name -> teatypes.GroupMember
	3,  // 6: teaproto.RemoveGroupMemberResponse.errors:type_name -> teaproto.RemoveGroupMemberResponse.Error
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_group_members_proto_init() }
func file_group_members_proto_init() {
	if File_group_members_proto != nil {
		return
	}
	file_teatypes_tgroups_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_group_members_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMembersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMembersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGroupMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_members_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGroupMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_group_members_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_members_proto_goTypes,
		DependencyIndexes: file_group_members_proto_depIdxs,
		EnumInfos:         file_group_members_proto_enumTypes,
		MessageInfos:      file_group_members_proto_msgTypes,
	}.Build()
	File_group_members_proto = out.File
	file_group_members_proto_rawDesc = nil
	file_group_members_proto_goTypes = nil
	file_group_members_proto_depIdxs = nil
}
