// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: messages.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageResponse_Error int32

const (
	SendMessageResponse_UNKNOWN_ERROR                   SendMessageResponse_Error = 0
	SendMessageResponse_INVALID_MESSAGE_ID_ERROR        SendMessageResponse_Error = 1
	SendMessageResponse_INVALID_RECIPIENT_ERROR         SendMessageResponse_Error = 2
	SendMessageResponse_ACCESS_DENIED_ERROR             SendMessageResponse_Error = 11
	SendMessageResponse_MESSAGE_TEXT_TOO_LONG_ERROR     SendMessageResponse_Error = 3 // see StateResponse.max_message_length
	SendMessageResponse_MESSAGE_IS_EMPTY_ERROR          SendMessageResponse_Error = 4 // message must have text, uploads or forward_id
	SendMessageResponse_TOO_MANY_UPLOADS_ERROR          SendMessageResponse_Error = 5 // see StateResponse.max_uploads_for_message
	SendMessageResponse_INVALID_FORWARDED_MESSAGE_ERROR SendMessageResponse_Error = 7
	SendMessageResponse_INVALID_REPLIED_MESSAGE_ERROR   SendMessageResponse_Error = 8  // message must be from the same chat
	SendMessageResponse_INVALID_AUDIO_UPLOAD_ID_ERROR   SendMessageResponse_Error = 9  // audio_upload_id must be valid and has audio type
	SendMessageResponse_AUDIO_TOO_LONG_ERROR            SendMessageResponse_Error = 10 // see StateResponse.max_audio_length_in_seconds. Application should split long audio into multiple messages
)

// Enum value maps for SendMessageResponse_Error.
var (
	SendMessageResponse_Error_name = map[int32]string{
		0:  "UNKNOWN_ERROR",
		1:  "INVALID_MESSAGE_ID_ERROR",
		2:  "INVALID_RECIPIENT_ERROR",
		11: "ACCESS_DENIED_ERROR",
		3:  "MESSAGE_TEXT_TOO_LONG_ERROR",
		4:  "MESSAGE_IS_EMPTY_ERROR",
		5:  "TOO_MANY_UPLOADS_ERROR",
		7:  "INVALID_FORWARDED_MESSAGE_ERROR",
		8:  "INVALID_REPLIED_MESSAGE_ERROR",
		9:  "INVALID_AUDIO_UPLOAD_ID_ERROR",
		10: "AUDIO_TOO_LONG_ERROR",
	}
	SendMessageResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":                   0,
		"INVALID_MESSAGE_ID_ERROR":        1,
		"INVALID_RECIPIENT_ERROR":         2,
		"ACCESS_DENIED_ERROR":             11,
		"MESSAGE_TEXT_TOO_LONG_ERROR":     3,
		"MESSAGE_IS_EMPTY_ERROR":          4,
		"TOO_MANY_UPLOADS_ERROR":          5,
		"INVALID_FORWARDED_MESSAGE_ERROR": 7,
		"INVALID_REPLIED_MESSAGE_ERROR":   8,
		"INVALID_AUDIO_UPLOAD_ID_ERROR":   9,
		"AUDIO_TOO_LONG_ERROR":            10,
	}
)

func (x SendMessageResponse_Error) Enum() *SendMessageResponse_Error {
	p := new(SendMessageResponse_Error)
	*p = x
	return p
}

func (x SendMessageResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendMessageResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (SendMessageResponse_Error) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x SendMessageResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendMessageResponse_Error.Descriptor instead.
func (SendMessageResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1, 0}
}

type DeleteMessageResponse_Error int32

const (
	DeleteMessageResponse_UNKNOWN_ERROR            DeleteMessageResponse_Error = 0
	DeleteMessageResponse_INVALID_MESSAGE_ID_ERROR DeleteMessageResponse_Error = 1
	DeleteMessageResponse_NOT_ALLOWED_ERROR        DeleteMessageResponse_Error = 2
)

// Enum value maps for DeleteMessageResponse_Error.
var (
	DeleteMessageResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_MESSAGE_ID_ERROR",
		2: "NOT_ALLOWED_ERROR",
	}
	DeleteMessageResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":            0,
		"INVALID_MESSAGE_ID_ERROR": 1,
		"NOT_ALLOWED_ERROR":        2,
	}
)

func (x DeleteMessageResponse_Error) Enum() *DeleteMessageResponse_Error {
	p := new(DeleteMessageResponse_Error)
	*p = x
	return p
}

func (x DeleteMessageResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteMessageResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (DeleteMessageResponse_Error) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x DeleteMessageResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteMessageResponse_Error.Descriptor instead.
func (DeleteMessageResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3, 0}
}

type MessagesListRequest_PositionType int32

const (
	MessagesListRequest_LAST_MESSAGES_IN_CHAT        MessagesListRequest_PositionType = 0
	MessagesListRequest_LAST_VIEWED_MESSAGES_IN_CHAT MessagesListRequest_PositionType = 1
)

// Enum value maps for MessagesListRequest_PositionType.
var (
	MessagesListRequest_PositionType_name = map[int32]string{
		0: "LAST_MESSAGES_IN_CHAT",
		1: "LAST_VIEWED_MESSAGES_IN_CHAT",
	}
	MessagesListRequest_PositionType_value = map[string]int32{
		"LAST_MESSAGES_IN_CHAT":        0,
		"LAST_VIEWED_MESSAGES_IN_CHAT": 1,
	}
)

func (x MessagesListRequest_PositionType) Enum() *MessagesListRequest_PositionType {
	p := new(MessagesListRequest_PositionType)
	*p = x
	return p
}

func (x MessagesListRequest_PositionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessagesListRequest_PositionType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[2].Descriptor()
}

func (MessagesListRequest_PositionType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[2]
}

func (x MessagesListRequest_PositionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessagesListRequest_PositionType.Descriptor instead.
func (MessagesListRequest_PositionType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 0}
}

type MessagesListResponse_Error int32

const (
	MessagesListResponse_UNKNOWN_ERROR            MessagesListResponse_Error = 0
	MessagesListResponse_INVALID_RECIPIENT_ERROR  MessagesListResponse_Error = 1
	MessagesListResponse_ACCESS_DENIED_ERROR      MessagesListResponse_Error = 4
	MessagesListResponse_INVALID_MESSAGE_ID_ERROR MessagesListResponse_Error = 2
	MessagesListResponse_INVALID_LIMIT_ERROR      MessagesListResponse_Error = 3
)

// Enum value maps for MessagesListResponse_Error.
var (
	MessagesListResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_RECIPIENT_ERROR",
		4: "ACCESS_DENIED_ERROR",
		2: "INVALID_MESSAGE_ID_ERROR",
		3: "INVALID_LIMIT_ERROR",
	}
	MessagesListResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":            0,
		"INVALID_RECIPIENT_ERROR":  1,
		"ACCESS_DENIED_ERROR":      4,
		"INVALID_MESSAGE_ID_ERROR": 2,
		"INVALID_LIMIT_ERROR":      3,
	}
)

func (x MessagesListResponse_Error) Enum() *MessagesListResponse_Error {
	p := new(MessagesListResponse_Error)
	*p = x
	return p
}

func (x MessagesListResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessagesListResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[3].Descriptor()
}

func (MessagesListResponse_Error) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[3]
}

func (x MessagesListResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessagesListResponse_Error.Descriptor instead.
func (MessagesListResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5, 0}
}

type MessageDetailsResponse_Error int32

const (
	MessageDetailsResponse_UNKNOWN_ERROR            MessageDetailsResponse_Error = 0
	MessageDetailsResponse_INVALID_MESSAGE_ID_ERROR MessageDetailsResponse_Error = 1
)

// Enum value maps for MessageDetailsResponse_Error.
var (
	MessageDetailsResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_MESSAGE_ID_ERROR",
	}
	MessageDetailsResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":            0,
		"INVALID_MESSAGE_ID_ERROR": 1,
	}
)

func (x MessageDetailsResponse_Error) Enum() *MessageDetailsResponse_Error {
	p := new(MessageDetailsResponse_Error)
	*p = x
	return p
}

func (x MessageDetailsResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageDetailsResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[4].Descriptor()
}

func (MessageDetailsResponse_Error) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[4]
}

func (x MessageDetailsResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageDetailsResponse_Error.Descriptor instead.
func (MessageDetailsResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7, 0}
}

type ViewMessageResponse_Error int32

const (
	ViewMessageResponse_UNKNOWN_ERROR            ViewMessageResponse_Error = 0
	ViewMessageResponse_INVALID_MESSAGE_ID_ERROR ViewMessageResponse_Error = 1
)

// Enum value maps for ViewMessageResponse_Error.
var (
	ViewMessageResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_MESSAGE_ID_ERROR",
	}
	ViewMessageResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":            0,
		"INVALID_MESSAGE_ID_ERROR": 1,
	}
)

func (x ViewMessageResponse_Error) Enum() *ViewMessageResponse_Error {
	p := new(ViewMessageResponse_Error)
	*p = x
	return p
}

func (x ViewMessageResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewMessageResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[5].Descriptor()
}

func (ViewMessageResponse_Error) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[5]
}

func (x ViewMessageResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewMessageResponse_Error.Descriptor instead.
func (ViewMessageResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10, 0}
}

type MessageViewersResponse_Error int32

const (
	MessageViewersResponse_UNKNOWN_ERROR            MessageViewersResponse_Error = 0
	MessageViewersResponse_INVALID_MESSAGE_ID_ERROR MessageViewersResponse_Error = 1
	MessageViewersResponse_INVALID_LIMIT_ERROR      MessageViewersResponse_Error = 2
)

// Enum value maps for MessageViewersResponse_Error.
var (
	MessageViewersResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_MESSAGE_ID_ERROR",
		2: "INVALID_LIMIT_ERROR",
	}
	MessageViewersResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":            0,
		"INVALID_MESSAGE_ID_ERROR": 1,
		"INVALID_LIMIT_ERROR":      2,
	}
)

func (x MessageViewersResponse_Error) Enum() *MessageViewersResponse_Error {
	p := new(MessageViewersResponse_Error)
	*p = x
	return p
}

func (x MessageViewersResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageViewersResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[6].Descriptor()
}

func (MessageViewersResponse_Error) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[6]
}

func (x MessageViewersResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageViewersResponse_Error.Descriptor instead.
func (MessageViewersResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12, 0}
}

type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"` // optional: when present used as id for new message or for editing existing message
	// Types that are assignable to Recipient:
	//
	//	*SendMessageRequest_ChatId
	//	*SendMessageRequest_UserId
	Recipient isSendMessageRequest_Recipient `protobuf_oneof:"recipient"`
	// Types that are assignable to Content:
	//
	//	*SendMessageRequest_Text
	//	*SendMessageRequest_ForwardId
	//	*SendMessageRequest_AudioUploadId
	Content isSendMessageRequest_Content `protobuf_oneof:"content"`
	// optional attachments
	ReplyId   string   `protobuf:"bytes,6,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UploadIds []string `protobuf:"bytes,5,rep,name=upload_ids,json=uploadIds,proto3" json:"upload_ids,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *SendMessageRequest) GetRecipient() isSendMessageRequest_Recipient {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (x *SendMessageRequest) GetChatId() string {
	if x, ok := x.GetRecipient().(*SendMessageRequest_ChatId); ok {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetUserId() string {
	if x, ok := x.GetRecipient().(*SendMessageRequest_UserId); ok {
		return x.UserId
	}
	return ""
}

func (m *SendMessageRequest) GetContent() isSendMessageRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *SendMessageRequest) GetText() string {
	if x, ok := x.GetContent().(*SendMessageRequest_Text); ok {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetForwardId() string {
	if x, ok := x.GetContent().(*SendMessageRequest_ForwardId); ok {
		return x.ForwardId
	}
	return ""
}

func (x *SendMessageRequest) GetAudioUploadId() string {
	if x, ok := x.GetContent().(*SendMessageRequest_AudioUploadId); ok {
		return x.AudioUploadId
	}
	return ""
}

func (x *SendMessageRequest) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *SendMessageRequest) GetUploadIds() []string {
	if x != nil {
		return x.UploadIds
	}
	return nil
}

type isSendMessageRequest_Recipient interface {
	isSendMessageRequest_Recipient()
}

type SendMessageRequest_ChatId struct {
	ChatId string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3,oneof"`
}

type SendMessageRequest_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*SendMessageRequest_ChatId) isSendMessageRequest_Recipient() {}

func (*SendMessageRequest_UserId) isSendMessageRequest_Recipient() {}

type isSendMessageRequest_Content interface {
	isSendMessageRequest_Content()
}

type SendMessageRequest_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type SendMessageRequest_ForwardId struct {
	ForwardId string `protobuf:"bytes,7,opt,name=forward_id,json=forwardId,proto3,oneof"`
}

type SendMessageRequest_AudioUploadId struct {
	AudioUploadId string `protobuf:"bytes,8,opt,name=audio_upload_id,json=audioUploadId,proto3,oneof"`
}

func (*SendMessageRequest_Text) isSendMessageRequest_Content() {}

func (*SendMessageRequest_ForwardId) isSendMessageRequest_Content() {}

func (*SendMessageRequest_AudioUploadId) isSendMessageRequest_Content() {}

type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors       []SendMessageResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.SendMessageResponse_Error" json:"errors,omitempty"`
	ErrorsHint   string                      `protobuf:"bytes,3,opt,name=errors_hint,json=errorsHint,proto3" json:"errors_hint,omitempty"` // optional human readable error description
	Message      *Message                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChatBadges   []*ChatBadge                `protobuf:"bytes,4,rep,name=chat_badges,json=chatBadges,proto3" json:"chat_badges,omitempty"`
	GlobalBadges []*GlobalBadge              `protobuf:"bytes,5,rep,name=global_badges,json=globalBadges,proto3" json:"global_badges,omitempty"`
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetErrors() []SendMessageResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SendMessageResponse) GetErrorsHint() string {
	if x != nil {
		return x.ErrorsHint
	}
	return ""
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageResponse) GetChatBadges() []*ChatBadge {
	if x != nil {
		return x.ChatBadges
	}
	return nil
}

func (x *SendMessageResponse) GetGlobalBadges() []*GlobalBadge {
	if x != nil {
		return x.GlobalBadges
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors  []DeleteMessageResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.DeleteMessageResponse_Error" json:"errors,omitempty"`
	Message *Message                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMessageResponse) GetErrors() []DeleteMessageResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *DeleteMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessagesListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Recipient:
	//
	//	*MessagesListRequest_ChatId
	//	*MessagesListRequest_UserId
	Recipient isMessagesListRequest_Recipient `protobuf_oneof:"recipient"`
	// Types that are assignable to Position:
	//
	//	*MessagesListRequest_Type
	//	*MessagesListRequest_MessageId
	Position         isMessagesListRequest_Position `protobuf_oneof:"position"`
	NewMessagesLimit uint32                         `protobuf:"varint,4,opt,name=new_messages_limit,json=newMessagesLimit,proto3" json:"new_messages_limit,omitempty"` // default: StateResponse.max_results_on_page
	OldMessagesLimit uint32                         `protobuf:"varint,5,opt,name=old_messages_limit,json=oldMessagesLimit,proto3" json:"old_messages_limit,omitempty"` // default: StateResponse.max_results_on_page
	// filters
	OnlyWithUploads     bool `protobuf:"varint,6,opt,name=only_with_uploads,json=onlyWithUploads,proto3" json:"only_with_uploads,omitempty"`
	SkipSystemMessages  bool `protobuf:"varint,7,opt,name=skip_system_messages,json=skipSystemMessages,proto3" json:"skip_system_messages,omitempty"`
	SkipDeletedMessages bool `protobuf:"varint,12,opt,name=skip_deleted_messages,json=skipDeletedMessages,proto3" json:"skip_deleted_messages,omitempty"`
	OnlyAudioUploads    bool `protobuf:"varint,8,opt,name=only_audio_uploads,json=onlyAudioUploads,proto3" json:"only_audio_uploads,omitempty"`
}

func (x *MessagesListRequest) Reset() {
	*x = MessagesListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesListRequest) ProtoMessage() {}

func (x *MessagesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesListRequest.ProtoReflect.Descriptor instead.
func (*MessagesListRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (m *MessagesListRequest) GetRecipient() isMessagesListRequest_Recipient {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (x *MessagesListRequest) GetChatId() string {
	if x, ok := x.GetRecipient().(*MessagesListRequest_ChatId); ok {
		return x.ChatId
	}
	return ""
}

func (x *MessagesListRequest) GetUserId() string {
	if x, ok := x.GetRecipient().(*MessagesListRequest_UserId); ok {
		return x.UserId
	}
	return ""
}

func (m *MessagesListRequest) GetPosition() isMessagesListRequest_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (x *MessagesListRequest) GetType() MessagesListRequest_PositionType {
	if x, ok := x.GetPosition().(*MessagesListRequest_Type); ok {
		return x.Type
	}
	return MessagesListRequest_LAST_MESSAGES_IN_CHAT
}

func (x *MessagesListRequest) GetMessageId() string {
	if x, ok := x.GetPosition().(*MessagesListRequest_MessageId); ok {
		return x.MessageId
	}
	return ""
}

func (x *MessagesListRequest) GetNewMessagesLimit() uint32 {
	if x != nil {
		return x.NewMessagesLimit
	}
	return 0
}

func (x *MessagesListRequest) GetOldMessagesLimit() uint32 {
	if x != nil {
		return x.OldMessagesLimit
	}
	return 0
}

func (x *MessagesListRequest) GetOnlyWithUploads() bool {
	if x != nil {
		return x.OnlyWithUploads
	}
	return false
}

func (x *MessagesListRequest) GetSkipSystemMessages() bool {
	if x != nil {
		return x.SkipSystemMessages
	}
	return false
}

func (x *MessagesListRequest) GetSkipDeletedMessages() bool {
	if x != nil {
		return x.SkipDeletedMessages
	}
	return false
}

func (x *MessagesListRequest) GetOnlyAudioUploads() bool {
	if x != nil {
		return x.OnlyAudioUploads
	}
	return false
}

type isMessagesListRequest_Recipient interface {
	isMessagesListRequest_Recipient()
}

type MessagesListRequest_ChatId struct {
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3,oneof"`
}

type MessagesListRequest_UserId struct {
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*MessagesListRequest_ChatId) isMessagesListRequest_Recipient() {}

func (*MessagesListRequest_UserId) isMessagesListRequest_Recipient() {}

type isMessagesListRequest_Position interface {
	isMessagesListRequest_Position()
}

type MessagesListRequest_Type struct {
	Type MessagesListRequest_PositionType `protobuf:"varint,10,opt,name=type,proto3,enum=teaproto.MessagesListRequest_PositionType,oneof"`
}

type MessagesListRequest_MessageId struct {
	MessageId string `protobuf:"bytes,9,opt,name=message_id,json=messageId,proto3,oneof"`
}

func (*MessagesListRequest_Type) isMessagesListRequest_Position() {}

func (*MessagesListRequest_MessageId) isMessagesListRequest_Position() {}

type MessagesListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors   []MessagesListResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.MessagesListResponse_Error" json:"errors,omitempty"`
	Messages []*Message                   `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MessagesListResponse) Reset() {
	*x = MessagesListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesListResponse) ProtoMessage() {}

func (x *MessagesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesListResponse.ProtoReflect.Descriptor instead.
func (*MessagesListResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MessagesListResponse) GetErrors() []MessagesListResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *MessagesListResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageDetailsRequest) Reset() {
	*x = MessageDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDetailsRequest) ProtoMessage() {}

func (x *MessageDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDetailsRequest.ProtoReflect.Descriptor instead.
func (*MessageDetailsRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MessageDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors  []MessageDetailsResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.MessageDetailsResponse_Error" json:"errors,omitempty"`
	Message *Message                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageDetailsResponse) Reset() {
	*x = MessageDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDetailsResponse) ProtoMessage() {}

func (x *MessageDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDetailsResponse.ProtoReflect.Descriptor instead.
func (*MessageDetailsResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *MessageDetailsResponse) GetErrors() []MessageDetailsResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *MessageDetailsResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ViewedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId     string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ViewedCounter uint32 `protobuf:"varint,3,opt,name=viewed_counter,json=viewedCounter,proto3" json:"viewed_counter,omitempty"` // how many recipients viewed this message
}

func (x *ViewedMessage) Reset() {
	*x = ViewedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewedMessage) ProtoMessage() {}

func (x *ViewedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewedMessage.ProtoReflect.Descriptor instead.
func (*ViewedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ViewedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ViewedMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ViewedMessage) GetViewedCounter() uint32 {
	if x != nil {
		return x.ViewedCounter
	}
	return 0
}

type ViewMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *ViewMessageRequest) Reset() {
	*x = ViewMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMessageRequest) ProtoMessage() {}

func (x *ViewMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMessageRequest.ProtoReflect.Descriptor instead.
func (*ViewMessageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ViewMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ViewMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors         []ViewMessageResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.ViewMessageResponse_Error" json:"errors,omitempty"`
	ViewedMessages []*ViewedMessage            `protobuf:"bytes,3,rep,name=viewed_messages,json=viewedMessages,proto3" json:"viewed_messages,omitempty"` // viewed messages list
	ChatBadges     []*ChatBadge                `protobuf:"bytes,4,rep,name=chat_badges,json=chatBadges,proto3" json:"chat_badges,omitempty"`             // number of unseen messages
	GlobalBadges   []*GlobalBadge              `protobuf:"bytes,5,rep,name=global_badges,json=globalBadges,proto3" json:"global_badges,omitempty"`
}

func (x *ViewMessageResponse) Reset() {
	*x = ViewMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMessageResponse) ProtoMessage() {}

func (x *ViewMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMessageResponse.ProtoReflect.Descriptor instead.
func (*ViewMessageResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ViewMessageResponse) GetErrors() []ViewMessageResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ViewMessageResponse) GetViewedMessages() []*ViewedMessage {
	if x != nil {
		return x.ViewedMessages
	}
	return nil
}

func (x *ViewMessageResponse) GetChatBadges() []*ChatBadge {
	if x != nil {
		return x.ChatBadges
	}
	return nil
}

func (x *ViewMessageResponse) GetGlobalBadges() []*GlobalBadge {
	if x != nil {
		return x.GlobalBadges
	}
	return nil
}

type MessageViewersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Limit     uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // default: StateResponse.max_results_on_page
	Offset    uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *MessageViewersRequest) Reset() {
	*x = MessageViewersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageViewersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageViewersRequest) ProtoMessage() {}

func (x *MessageViewersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageViewersRequest.ProtoReflect.Descriptor instead.
func (*MessageViewersRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *MessageViewersRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageViewersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MessageViewersRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MessageViewersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []MessageViewersResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.MessageViewersResponse_Error" json:"errors,omitempty"`
	Users  []*User                        `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *MessageViewersResponse) Reset() {
	*x = MessageViewersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageViewersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageViewersResponse) ProtoMessage() {}

func (x *MessageViewersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageViewersResponse.ProtoReflect.Descriptor instead.
func (*MessageViewersResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *MessageViewersResponse) GetErrors() []MessageViewersResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *MessageViewersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x74, 0x65, 0x61, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x15, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x63, 0x68,
	0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74, 0x65, 0x61, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x74, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8d, 0x02, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0d, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0xe1, 0x04, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x5f,
	0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x0a, 0x63,
	0x68, 0x61, 0x74, 0x42, 0x61, 0x64, 0x67, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x5f, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42,
	0x61, 0x64, 0x67, 0x65, 0x73, 0x22, 0xcc, 0x02, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x49, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x1b, 0x0a, 0x17, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x43, 0x49,
	0x50, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a,
	0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x0b, 0x12, 0x1f, 0x0a, 0x1b, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x4f, 0x4e, 0x47, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x49, 0x53, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x4f, 0x4f, 0x5f, 0x4d, 0x41, 0x4e, 0x59, 0x5f,
	0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05, 0x12,
	0x23, 0x0a, 0x1f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x46, 0x4f, 0x52, 0x57, 0x41,
	0x52, 0x44, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x07, 0x12, 0x21, 0x0a, 0x1d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x52, 0x45, 0x50, 0x4c, 0x49, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x08, 0x12, 0x21, 0x0a, 0x1d, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f,
	0x49, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x09, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x55,
	0x44, 0x49, 0x4f, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x4f, 0x4e, 0x47, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x0a, 0x22, 0x35, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xd4, 0x01, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x4f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x1c, 0x0a,
	0x18, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x49, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4e,
	0x4f, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x02, 0x22, 0xb0, 0x04, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x40, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a,
	0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x01, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x10, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x6c, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6f,
	0x6c, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x2a, 0x0a, 0x11, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6f, 0x6e, 0x6c, 0x79,
	0x57, 0x69, 0x74, 0x68, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x73,
	0x6b, 0x69, 0x70, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x73, 0x6b, 0x69, 0x70, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x15, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x73, 0x6b,
	0x69, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6f,
	0x6e, 0x6c, 0x79, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x22,
	0x4b, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x53,
	0x5f, 0x49, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x4c, 0x41,
	0x53, 0x54, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x53, 0x5f, 0x49, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x01, 0x42, 0x0b, 0x0a, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8d, 0x02, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x24,
	0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x43, 0x49, 0x50, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f,
	0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x1c,
	0x0a, 0x18, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x49, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x27, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbf,
	0x01, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x74, 0x65, 0x61, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x61,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x49, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x22, 0x6e, 0x0a, 0x0d, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x69, 0x65,
	0x77, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x76, 0x69, 0x65, 0x77, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x22, 0x33, 0x0a, 0x12, 0x56, 0x69, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xc0, 0x02, 0x0a, 0x13, 0x56, 0x69, 0x65, 0x77, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x23, 0x2e,
	0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x76, 0x69,
	0x65, 0x77, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x76, 0x69,
	0x65, 0x77, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0b,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x42, 0x61, 0x64, 0x67,
	0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x62, 0x61, 0x64,
	0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x61, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42, 0x61, 0x64, 0x67, 0x65,
	0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42, 0x61, 0x64, 0x67, 0x65, 0x73, 0x22, 0x38,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x49, 0x44,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x64, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xd1,
	0x01, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x74, 0x65, 0x61, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x51, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x49,
	0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_messages_proto_goTypes = []interface{}{
	(SendMessageResponse_Error)(0),        // 0: teaproto.SendMessageResponse.Error
	(DeleteMessageResponse_Error)(0),      // 1: teaproto.DeleteMessageResponse.Error
	(MessagesListRequest_PositionType)(0), // 2: teaproto.MessagesListRequest.PositionType
	(MessagesListResponse_Error)(0),       // 3: teaproto.MessagesListResponse.Error
	(MessageDetailsResponse_Error)(0),     // 4: teaproto.MessageDetailsResponse.Error
	(ViewMessageResponse_Error)(0),        // 5: teaproto.ViewMessageResponse.Error
	(MessageViewersResponse_Error)(0),     // 6: teaproto.MessageViewersResponse.Error
	(*SendMessageRequest)(nil),            // 7: teaproto.SendMessageRequest
	(*SendMessageResponse)(nil),           // 8: teaproto.SendMessageResponse
	(*DeleteMessageRequest)(nil),          // 9: teaproto.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),         // 10: teaproto.DeleteMessageResponse
	(*MessagesListRequest)(nil),           // 11: teaproto.MessagesListRequest
	(*MessagesListResponse)(nil),          // 12: teaproto.MessagesListResponse
	(*MessageDetailsRequest)(nil),         // 13: teaproto.MessageDetailsRequest
	(*MessageDetailsResponse)(nil),        // 14: teaproto.MessageDetailsResponse
	(*ViewedMessage)(nil),                 // 15: teaproto.ViewedMessage
	(*ViewMessageRequest)(nil),            // 16: teaproto.ViewMessageRequest
	(*ViewMessageResponse)(nil),           // 17: teaproto.ViewMessageResponse
	(*MessageViewersRequest)(nil),         // 18: teaproto.MessageViewersRequest
	(*MessageViewersResponse)(nil),        // 19: teaproto.MessageViewersResponse
	(*Message)(nil),                       // 20: teatypes.Message
	(*ChatBadge)(nil),                     // 21: teatypes.ChatBadge
	(*GlobalBadge)(nil),                   // 22: teatypes.GlobalBadge
	(*User)(nil),                          // 23: teatypes.User
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: teaproto.SendMessageResponse.errors:type_name -> teaproto.SendMessageResponse.Error
	20, // 1: teaproto.SendMessageResponse.message:type_name -> teatypes.Message
	21, // 2: teaproto.SendMessageResponse.chat_badges:type_name -> teatypes.ChatBadge
	22, // 3: teaproto.SendMessageResponse.global_badges:type_name -> teatypes.GlobalBadge
	1,  // 4: teaproto.DeleteMessageResponse.errors:type_name -> teaproto.DeleteMessageResponse.Error
	20, // 5: teaproto.DeleteMessageResponse.message:type_name -> teatypes.Message
	2,  // 6: teaproto.MessagesListRequest.type:type_name -> teaproto.MessagesListRequest.PositionType
	3,  // 7: teaproto.MessagesListResponse.errors:type_name -> teaproto.MessagesListResponse.Error
	20, // 8: teaproto.MessagesListResponse.messages:type_name -> teatypes.Message
	4,  // 9: teaproto.MessageDetailsResponse.errors:type_name -> teaproto.MessageDetailsResponse.Error
	20, // 10: teaproto.MessageDetailsResponse.message:type_name -> teatypes.Message
	5,  // 11: teaproto.ViewMessageResponse.errors:type_name -> teaproto.ViewMessageResponse.Error
	15, // 12: teaproto.ViewMessageResponse.viewed_messages:type_name -> teaproto.ViewedMessage
	21, // 13: teaproto.ViewMessageResponse.chat_badges:type_name -> teatypes.ChatBadge
	22, // 14: teaproto.ViewMessageResponse.global_badges:type_name -> teatypes.GlobalBadge
	6,  // 15: teaproto.MessageViewersResponse.errors:type_name -> teaproto.MessageViewersResponse.Error
	23, // 16: teaproto.MessageViewersResponse.users:type_name -> teatypes.User
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_teatypes_tbadges_proto_init()
	file_teatypes_tchats_proto_init()
	file_teatypes_tusers_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagesListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagesListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageViewersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageViewersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SendMessageRequest_ChatId)(nil),
		(*SendMessageRequest_UserId)(nil),
		(*SendMessageRequest_Text)(nil),
		(*SendMessageRequest_ForwardId)(nil),
		(*SendMessageRequest_AudioUploadId)(nil),
	}
	file_messages_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*MessagesListRequest_ChatId)(nil),
		(*MessagesListRequest_UserId)(nil),
		(*MessagesListRequest_Type)(nil),
		(*MessagesListRequest_MessageId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
