// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: task_members.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskMembersListResponse_Error int32

const (
	TaskMembersListResponse_UNKNOWN_ERROR       TaskMembersListResponse_Error = 0
	TaskMembersListResponse_INVALID_CHAT_ERROR  TaskMembersListResponse_Error = 1
	TaskMembersListResponse_ACCESS_DENIED_ERROR TaskMembersListResponse_Error = 2
	TaskMembersListResponse_INVALID_LIMIT_ERROR TaskMembersListResponse_Error = 3
)

// Enum value maps for TaskMembersListResponse_Error.
var (
	TaskMembersListResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
		3: "INVALID_LIMIT_ERROR",
	}
	TaskMembersListResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
		"INVALID_LIMIT_ERROR": 3,
	}
)

func (x TaskMembersListResponse_Error) Enum() *TaskMembersListResponse_Error {
	p := new(TaskMembersListResponse_Error)
	*p = x
	return p
}

func (x TaskMembersListResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskMembersListResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_task_members_proto_enumTypes[0].Descriptor()
}

func (TaskMembersListResponse_Error) Type() protoreflect.EnumType {
	return &file_task_members_proto_enumTypes[0]
}

func (x TaskMembersListResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskMembersListResponse_Error.Descriptor instead.
func (TaskMembersListResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{1, 0}
}

type CreateOrUpdateTaskMembersResponse_Error int32

const (
	CreateOrUpdateTaskMembersResponse_UNKNOWN_ERROR       CreateOrUpdateTaskMembersResponse_Error = 0
	CreateOrUpdateTaskMembersResponse_INVALID_CHAT_ERROR  CreateOrUpdateTaskMembersResponse_Error = 1
	CreateOrUpdateTaskMembersResponse_ACCESS_DENIED_ERROR CreateOrUpdateTaskMembersResponse_Error = 2
)

// Enum value maps for CreateOrUpdateTaskMembersResponse_Error.
var (
	CreateOrUpdateTaskMembersResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
	}
	CreateOrUpdateTaskMembersResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
	}
)

func (x CreateOrUpdateTaskMembersResponse_Error) Enum() *CreateOrUpdateTaskMembersResponse_Error {
	p := new(CreateOrUpdateTaskMembersResponse_Error)
	*p = x
	return p
}

func (x CreateOrUpdateTaskMembersResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrUpdateTaskMembersResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_task_members_proto_enumTypes[1].Descriptor()
}

func (CreateOrUpdateTaskMembersResponse_Error) Type() protoreflect.EnumType {
	return &file_task_members_proto_enumTypes[1]
}

func (x CreateOrUpdateTaskMembersResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrUpdateTaskMembersResponse_Error.Descriptor instead.
func (CreateOrUpdateTaskMembersResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{3, 0}
}

type RemoveTaskMembersResponse_Error int32

const (
	RemoveTaskMembersResponse_UNKNOWN_ERROR       RemoveTaskMembersResponse_Error = 0
	RemoveTaskMembersResponse_INVALID_CHAT_ERROR  RemoveTaskMembersResponse_Error = 1
	RemoveTaskMembersResponse_ACCESS_DENIED_ERROR RemoveTaskMembersResponse_Error = 2
)

// Enum value maps for RemoveTaskMembersResponse_Error.
var (
	RemoveTaskMembersResponse_Error_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INVALID_CHAT_ERROR",
		2: "ACCESS_DENIED_ERROR",
	}
	RemoveTaskMembersResponse_Error_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"INVALID_CHAT_ERROR":  1,
		"ACCESS_DENIED_ERROR": 2,
	}
)

func (x RemoveTaskMembersResponse_Error) Enum() *RemoveTaskMembersResponse_Error {
	p := new(RemoveTaskMembersResponse_Error)
	*p = x
	return p
}

func (x RemoveTaskMembersResponse_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveTaskMembersResponse_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_task_members_proto_enumTypes[2].Descriptor()
}

func (RemoveTaskMembersResponse_Error) Type() protoreflect.EnumType {
	return &file_task_members_proto_enumTypes[2]
}

func (x RemoveTaskMembersResponse_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveTaskMembersResponse_Error.Descriptor instead.
func (RemoveTaskMembersResponse_Error) EnumDescriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{5, 0}
}

type TaskMembersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // default: StateResponse.max_results_on_page
	Offset uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// filters
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid or "me"
}

func (x *TaskMembersListRequest) Reset() {
	*x = TaskMembersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_members_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskMembersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMembersListRequest) ProtoMessage() {}

func (x *TaskMembersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_members_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMembersListRequest.ProtoReflect.Descriptor instead.
func (*TaskMembersListRequest) Descriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMembersListRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TaskMembersListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TaskMembersListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TaskMembersListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TaskMembersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors  []TaskMembersListResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.TaskMembersListResponse_Error" json:"errors,omitempty"`
	Members []*TaskMember                   `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *TaskMembersListResponse) Reset() {
	*x = TaskMembersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_members_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskMembersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMembersListResponse) ProtoMessage() {}

func (x *TaskMembersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_members_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMembersListResponse.ProtoReflect.Descriptor instead.
func (*TaskMembersListResponse) Descriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMembersListResponse) GetErrors() []TaskMembersListResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *TaskMembersListResponse) GetMembers() []*TaskMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateOrUpdateTaskMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  string              `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Members []*TaskMemberUpdate `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *CreateOrUpdateTaskMembersRequest) Reset() {
	*x = CreateOrUpdateTaskMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_members_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateTaskMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateTaskMembersRequest) ProtoMessage() {}

func (x *CreateOrUpdateTaskMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_members_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateTaskMembersRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateTaskMembersRequest) Descriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrUpdateTaskMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateOrUpdateTaskMembersRequest) GetMembers() []*TaskMemberUpdate {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateOrUpdateTaskMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors              []CreateOrUpdateTaskMembersResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.CreateOrUpdateTaskMembersResponse_Error" json:"errors,omitempty"`
	NewOrUpdatedMembers []*TaskMember                             `protobuf:"bytes,2,rep,name=new_or_updated_members,json=newOrUpdatedMembers,proto3" json:"new_or_updated_members,omitempty"`
	Chat                *Chat                                     `protobuf:"bytes,3,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *CreateOrUpdateTaskMembersResponse) Reset() {
	*x = CreateOrUpdateTaskMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_members_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateTaskMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateTaskMembersResponse) ProtoMessage() {}

func (x *CreateOrUpdateTaskMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_members_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateTaskMembersResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateTaskMembersResponse) Descriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrUpdateTaskMembersResponse) GetErrors() []CreateOrUpdateTaskMembersResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CreateOrUpdateTaskMembersResponse) GetNewOrUpdatedMembers() []*TaskMember {
	if x != nil {
		return x.NewOrUpdatedMembers
	}
	return nil
}

func (x *CreateOrUpdateTaskMembersResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type RemoveTaskMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // uuid or "me"
}

func (x *RemoveTaskMembersRequest) Reset() {
	*x = RemoveTaskMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_members_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTaskMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskMembersRequest) ProtoMessage() {}

func (x *RemoveTaskMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_members_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveTaskMembersRequest) Descriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveTaskMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveTaskMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveTaskMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []RemoveTaskMembersResponse_Error `protobuf:"varint,1,rep,packed,name=errors,proto3,enum=teaproto.RemoveTaskMembersResponse_Error" json:"errors,omitempty"`
	Chat   *Chat                             `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *RemoveTaskMembersResponse) Reset() {
	*x = RemoveTaskMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_members_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTaskMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskMembersResponse) ProtoMessage() {}

func (x *RemoveTaskMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_members_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskMembersResponse.ProtoReflect.Descriptor instead.
func (*RemoveTaskMembersResponse) Descriptor() ([]byte, []int) {
	return file_task_members_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveTaskMembersResponse) GetErrors() []RemoveTaskMembersResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *RemoveTaskMembersResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

var File_task_members_proto protoreflect.FileDescriptor

var file_task_members_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x16, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xf0,
	0x01, 0x0a, 0x17, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x61,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x64, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12,
	0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x03, 0x22, 0x71, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x34,
	0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0xaa, 0x02, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x74, 0x65, 0x61,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x49, 0x0a, 0x16, 0x6e, 0x65, 0x77, 0x5f, 0x6f, 0x72, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x13, 0x6e, 0x65, 0x77,
	0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x22, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04,
	0x63, 0x68, 0x61, 0x74, 0x22, 0x4b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a,
	0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x54,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x22, 0x4e, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x22, 0xcf, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x4b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48,
	0x41, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_members_proto_rawDescOnce sync.Once
	file_task_members_proto_rawDescData = file_task_members_proto_rawDesc
)

func file_task_members_proto_rawDescGZIP() []byte {
	file_task_members_proto_rawDescOnce.Do(func() {
		file_task_members_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_members_proto_rawDescData)
	})
	return file_task_members_proto_rawDescData
}

var file_task_members_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_task_members_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_task_members_proto_goTypes = []interface{}{
	(TaskMembersListResponse_Error)(0),           // 0: teaproto.TaskMembersListResponse.Error
	(CreateOrUpdateTaskMembersResponse_Error)(0), // 1: teaproto.CreateOrUpdateTaskMembersResponse.Error
	(RemoveTaskMembersResponse_Error)(0),         // 2: teaproto.RemoveTaskMembersResponse.Error
	(*TaskMembersListRequest)(nil),               // 3: teaproto.TaskMembersListRequest
	(*TaskMembersListResponse)(nil),              // 4: teaproto.TaskMembersListResponse
	(*CreateOrUpdateTaskMembersRequest)(nil),     // 5: teaproto.CreateOrUpdateTaskMembersRequest
	(*CreateOrUpdateTaskMembersResponse)(nil),    // 6: teaproto.CreateOrUpdateTaskMembersResponse
	(*RemoveTaskMembersRequest)(nil),             // 7: teaproto.RemoveTaskMembersRequest
	(*RemoveTaskMembersResponse)(nil),            // 8: teaproto.RemoveTaskMembersResponse
	(*TaskMember)(nil),                           // 9: teaproto.TaskMember
	(*TaskMemberUpdate)(nil),                     // 10: teaproto.TaskMemberUpdate
	(*Chat)(nil),                                 // 11: teaproto.Chat
}
var file_task_members_proto_depIdxs = []int32{
	0,  // 0: teaproto.TaskMembersListResponse.errors:type_name -> teaproto.TaskMembersListResponse.Error
	9,  // 1: teaproto.TaskMembersListResponse.members:type_name -> teaproto.TaskMember
	10, // 2: teaproto.CreateOrUpdateTaskMembersRequest.members:type_name -> teaproto.TaskMemberUpdate
	1,  // 3: teaproto.CreateOrUpdateTaskMembersResponse.errors:type_name -> teaproto.CreateOrUpdateTaskMembersResponse.Error
	9,  // 4: teaproto.CreateOrUpdateTaskMembersResponse.new_or_updated_members:type_name -> teaproto.TaskMember
	11, // 5: teaproto.CreateOrUpdateTaskMembersResponse.chat:type_name -> teaproto.Chat
	2,  // 6: teaproto.RemoveTaskMembersResponse.errors:type_name -> teaproto.RemoveTaskMembersResponse.Error
	11, // 7: teaproto.RemoveTaskMembersResponse.chat:type_name -> teaproto.Chat
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_task_members_proto_init() }
func file_task_members_proto_init() {
	if File_task_members_proto != nil {
		return
	}
	file_types_tasks_proto_init()
	file_types_chats_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_task_members_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskMembersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_members_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskMembersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_members_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateTaskMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_members_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateTaskMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_members_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTaskMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_members_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTaskMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_members_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_members_proto_goTypes,
		DependencyIndexes: file_task_members_proto_depIdxs,
		EnumInfos:         file_task_members_proto_enumTypes,
		MessageInfos:      file_task_members_proto_msgTypes,
	}.Build()
	File_task_members_proto = out.File
	file_task_members_proto_rawDesc = nil
	file_task_members_proto_goTypes = nil
	file_task_members_proto_depIdxs = nil
}
