// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: teatypes/tsystem_messages.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *User `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	// Types that are assignable to Type:
	//
	//	*SystemMessage_ErrorMessage
	//	*SystemMessage_GroupCreated
	//	*SystemMessage_GroupRenamed
	//	*SystemMessage_GroupIconChanged
	//	*SystemMessage_UsersAddedToGroup
	//	*SystemMessage_UsersRemovedFromGroup
	//	*SystemMessage_TaskCreated
	//	*SystemMessage_TaskRenamed
	//	*SystemMessage_TaskDescriptionChanged
	//	*SystemMessage_UsersAddedToTask
	//	*SystemMessage_UsersRemovedFromTask
	//	*SystemMessage_TaskStatusChanged
	//	*SystemMessage_Welcome
	Type         isSystemMessage_Type `protobuf_oneof:"type"`
	FallbackText string               `protobuf:"bytes,2,opt,name=fallback_text,json=fallbackText,proto3" json:"fallback_text,omitempty"`
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage.ProtoReflect.Descriptor instead.
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMessage) GetActor() *User {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (m *SystemMessage) GetType() isSystemMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *SystemMessage) GetErrorMessage() *SystemMessage_ErrorMessageType {
	if x, ok := x.GetType().(*SystemMessage_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return nil
}

func (x *SystemMessage) GetGroupCreated() *SystemMessage_GroupCreatedType {
	if x, ok := x.GetType().(*SystemMessage_GroupCreated); ok {
		return x.GroupCreated
	}
	return nil
}

func (x *SystemMessage) GetGroupRenamed() *SystemMessage_GroupRenamedType {
	if x, ok := x.GetType().(*SystemMessage_GroupRenamed); ok {
		return x.GroupRenamed
	}
	return nil
}

func (x *SystemMessage) GetGroupIconChanged() *SystemMessage_GroupIconChangedType {
	if x, ok := x.GetType().(*SystemMessage_GroupIconChanged); ok {
		return x.GroupIconChanged
	}
	return nil
}

func (x *SystemMessage) GetUsersAddedToGroup() *SystemMessage_UsersAddedToGroupType {
	if x, ok := x.GetType().(*SystemMessage_UsersAddedToGroup); ok {
		return x.UsersAddedToGroup
	}
	return nil
}

func (x *SystemMessage) GetUsersRemovedFromGroup() *SystemMessage_UsersRemovedFromGroupType {
	if x, ok := x.GetType().(*SystemMessage_UsersRemovedFromGroup); ok {
		return x.UsersRemovedFromGroup
	}
	return nil
}

func (x *SystemMessage) GetTaskCreated() *SystemMessage_TaskCreatedType {
	if x, ok := x.GetType().(*SystemMessage_TaskCreated); ok {
		return x.TaskCreated
	}
	return nil
}

func (x *SystemMessage) GetTaskRenamed() *SystemMessage_TaskRenamedType {
	if x, ok := x.GetType().(*SystemMessage_TaskRenamed); ok {
		return x.TaskRenamed
	}
	return nil
}

func (x *SystemMessage) GetTaskDescriptionChanged() *SystemMessage_TaskDescriptionChangedType {
	if x, ok := x.GetType().(*SystemMessage_TaskDescriptionChanged); ok {
		return x.TaskDescriptionChanged
	}
	return nil
}

func (x *SystemMessage) GetUsersAddedToTask() *SystemMessage_UsersAddedToTaskType {
	if x, ok := x.GetType().(*SystemMessage_UsersAddedToTask); ok {
		return x.UsersAddedToTask
	}
	return nil
}

func (x *SystemMessage) GetUsersRemovedFromTask() *SystemMessage_UsersRemovedFromTaskType {
	if x, ok := x.GetType().(*SystemMessage_UsersRemovedFromTask); ok {
		return x.UsersRemovedFromTask
	}
	return nil
}

func (x *SystemMessage) GetTaskStatusChanged() *SystemMessage_TaskStatusChangedType {
	if x, ok := x.GetType().(*SystemMessage_TaskStatusChanged); ok {
		return x.TaskStatusChanged
	}
	return nil
}

func (x *SystemMessage) GetWelcome() *SystemMessage_WelcomeType {
	if x, ok := x.GetType().(*SystemMessage_Welcome); ok {
		return x.Welcome
	}
	return nil
}

func (x *SystemMessage) GetFallbackText() string {
	if x != nil {
		return x.FallbackText
	}
	return ""
}

type isSystemMessage_Type interface {
	isSystemMessage_Type()
}

type SystemMessage_ErrorMessage struct {
	ErrorMessage *SystemMessage_ErrorMessageType `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

type SystemMessage_GroupCreated struct {
	// groups
	GroupCreated *SystemMessage_GroupCreatedType `protobuf:"bytes,10,opt,name=group_created,json=groupCreated,proto3,oneof"`
}

type SystemMessage_GroupRenamed struct {
	GroupRenamed *SystemMessage_GroupRenamedType `protobuf:"bytes,11,opt,name=group_renamed,json=groupRenamed,proto3,oneof"`
}

type SystemMessage_GroupIconChanged struct {
	GroupIconChanged *SystemMessage_GroupIconChangedType `protobuf:"bytes,14,opt,name=group_icon_changed,json=groupIconChanged,proto3,oneof"`
}

type SystemMessage_UsersAddedToGroup struct {
	UsersAddedToGroup *SystemMessage_UsersAddedToGroupType `protobuf:"bytes,12,opt,name=users_added_to_group,json=usersAddedToGroup,proto3,oneof"`
}

type SystemMessage_UsersRemovedFromGroup struct {
	UsersRemovedFromGroup *SystemMessage_UsersRemovedFromGroupType `protobuf:"bytes,13,opt,name=users_removed_from_group,json=usersRemovedFromGroup,proto3,oneof"`
}

type SystemMessage_TaskCreated struct {
	// tasks
	TaskCreated *SystemMessage_TaskCreatedType `protobuf:"bytes,18,opt,name=task_created,json=taskCreated,proto3,oneof"`
}

type SystemMessage_TaskRenamed struct {
	TaskRenamed *SystemMessage_TaskRenamedType `protobuf:"bytes,19,opt,name=task_renamed,json=taskRenamed,proto3,oneof"`
}

type SystemMessage_TaskDescriptionChanged struct {
	TaskDescriptionChanged *SystemMessage_TaskDescriptionChangedType `protobuf:"bytes,21,opt,name=task_description_changed,json=taskDescriptionChanged,proto3,oneof"`
}

type SystemMessage_UsersAddedToTask struct {
	UsersAddedToTask *SystemMessage_UsersAddedToTaskType `protobuf:"bytes,16,opt,name=users_added_to_task,json=usersAddedToTask,proto3,oneof"`
}

type SystemMessage_UsersRemovedFromTask struct {
	UsersRemovedFromTask *SystemMessage_UsersRemovedFromTaskType `protobuf:"bytes,17,opt,name=users_removed_from_task,json=usersRemovedFromTask,proto3,oneof"`
}

type SystemMessage_TaskStatusChanged struct {
	TaskStatusChanged *SystemMessage_TaskStatusChangedType `protobuf:"bytes,20,opt,name=task_status_changed,json=taskStatusChanged,proto3,oneof"`
}

type SystemMessage_Welcome struct {
	// etc
	Welcome *SystemMessage_WelcomeType `protobuf:"bytes,15,opt,name=welcome,proto3,oneof"`
}

func (*SystemMessage_ErrorMessage) isSystemMessage_Type() {}

func (*SystemMessage_GroupCreated) isSystemMessage_Type() {}

func (*SystemMessage_GroupRenamed) isSystemMessage_Type() {}

func (*SystemMessage_GroupIconChanged) isSystemMessage_Type() {}

func (*SystemMessage_UsersAddedToGroup) isSystemMessage_Type() {}

func (*SystemMessage_UsersRemovedFromGroup) isSystemMessage_Type() {}

func (*SystemMessage_TaskCreated) isSystemMessage_Type() {}

func (*SystemMessage_TaskRenamed) isSystemMessage_Type() {}

func (*SystemMessage_TaskDescriptionChanged) isSystemMessage_Type() {}

func (*SystemMessage_UsersAddedToTask) isSystemMessage_Type() {}

func (*SystemMessage_UsersRemovedFromTask) isSystemMessage_Type() {}

func (*SystemMessage_TaskStatusChanged) isSystemMessage_Type() {}

func (*SystemMessage_Welcome) isSystemMessage_Type() {}

type SystemMessage_ErrorMessageType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SystemMessage_ErrorMessageType) Reset() {
	*x = SystemMessage_ErrorMessageType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_ErrorMessageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_ErrorMessageType) ProtoMessage() {}

func (x *SystemMessage_ErrorMessageType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_ErrorMessageType.ProtoReflect.Descriptor instead.
func (*SystemMessage_ErrorMessageType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SystemMessage_ErrorMessageType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SystemMessage_GroupCreatedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *SystemMessage_GroupCreatedType) Reset() {
	*x = SystemMessage_GroupCreatedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_GroupCreatedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_GroupCreatedType) ProtoMessage() {}

func (x *SystemMessage_GroupCreatedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_GroupCreatedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_GroupCreatedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SystemMessage_GroupCreatedType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SystemMessage_GroupRenamedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewTitle string `protobuf:"bytes,1,opt,name=new_title,json=newTitle,proto3" json:"new_title,omitempty"`
}

func (x *SystemMessage_GroupRenamedType) Reset() {
	*x = SystemMessage_GroupRenamedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_GroupRenamedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_GroupRenamedType) ProtoMessage() {}

func (x *SystemMessage_GroupRenamedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_GroupRenamedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_GroupRenamedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SystemMessage_GroupRenamedType) GetNewTitle() string {
	if x != nil {
		return x.NewTitle
	}
	return ""
}

type SystemMessage_GroupIconChangedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewIcon *Icon `protobuf:"bytes,1,opt,name=new_icon,json=newIcon,proto3" json:"new_icon,omitempty"`
}

func (x *SystemMessage_GroupIconChangedType) Reset() {
	*x = SystemMessage_GroupIconChangedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_GroupIconChangedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_GroupIconChangedType) ProtoMessage() {}

func (x *SystemMessage_GroupIconChangedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_GroupIconChangedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_GroupIconChangedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 3}
}

func (x *SystemMessage_GroupIconChangedType) GetNewIcon() *Icon {
	if x != nil {
		return x.NewIcon
	}
	return nil
}

type SystemMessage_UsersAddedToGroupType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SystemMessage_UsersAddedToGroupType) Reset() {
	*x = SystemMessage_UsersAddedToGroupType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_UsersAddedToGroupType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_UsersAddedToGroupType) ProtoMessage() {}

func (x *SystemMessage_UsersAddedToGroupType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_UsersAddedToGroupType.ProtoReflect.Descriptor instead.
func (*SystemMessage_UsersAddedToGroupType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 4}
}

func (x *SystemMessage_UsersAddedToGroupType) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SystemMessage_UsersRemovedFromGroupType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SystemMessage_UsersRemovedFromGroupType) Reset() {
	*x = SystemMessage_UsersRemovedFromGroupType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_UsersRemovedFromGroupType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_UsersRemovedFromGroupType) ProtoMessage() {}

func (x *SystemMessage_UsersRemovedFromGroupType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_UsersRemovedFromGroupType.ProtoReflect.Descriptor instead.
func (*SystemMessage_UsersRemovedFromGroupType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 5}
}

func (x *SystemMessage_UsersRemovedFromGroupType) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SystemMessage_TaskCreatedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *SystemMessage_TaskCreatedType) Reset() {
	*x = SystemMessage_TaskCreatedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_TaskCreatedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_TaskCreatedType) ProtoMessage() {}

func (x *SystemMessage_TaskCreatedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_TaskCreatedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_TaskCreatedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 6}
}

func (x *SystemMessage_TaskCreatedType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SystemMessage_TaskCreatedType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SystemMessage_TaskRenamedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewTitle string `protobuf:"bytes,1,opt,name=new_title,json=newTitle,proto3" json:"new_title,omitempty"`
}

func (x *SystemMessage_TaskRenamedType) Reset() {
	*x = SystemMessage_TaskRenamedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_TaskRenamedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_TaskRenamedType) ProtoMessage() {}

func (x *SystemMessage_TaskRenamedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_TaskRenamedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_TaskRenamedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 7}
}

func (x *SystemMessage_TaskRenamedType) GetNewTitle() string {
	if x != nil {
		return x.NewTitle
	}
	return ""
}

type SystemMessage_TaskDescriptionChangedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewDescription string `protobuf:"bytes,1,opt,name=new_description,json=newDescription,proto3" json:"new_description,omitempty"`
}

func (x *SystemMessage_TaskDescriptionChangedType) Reset() {
	*x = SystemMessage_TaskDescriptionChangedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_TaskDescriptionChangedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_TaskDescriptionChangedType) ProtoMessage() {}

func (x *SystemMessage_TaskDescriptionChangedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_TaskDescriptionChangedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_TaskDescriptionChangedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 8}
}

func (x *SystemMessage_TaskDescriptionChangedType) GetNewDescription() string {
	if x != nil {
		return x.NewDescription
	}
	return ""
}

type SystemMessage_UsersAddedToTaskType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SystemMessage_UsersAddedToTaskType) Reset() {
	*x = SystemMessage_UsersAddedToTaskType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_UsersAddedToTaskType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_UsersAddedToTaskType) ProtoMessage() {}

func (x *SystemMessage_UsersAddedToTaskType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_UsersAddedToTaskType.ProtoReflect.Descriptor instead.
func (*SystemMessage_UsersAddedToTaskType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 9}
}

func (x *SystemMessage_UsersAddedToTaskType) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SystemMessage_UsersRemovedFromTaskType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SystemMessage_UsersRemovedFromTaskType) Reset() {
	*x = SystemMessage_UsersRemovedFromTaskType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_UsersRemovedFromTaskType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_UsersRemovedFromTaskType) ProtoMessage() {}

func (x *SystemMessage_UsersRemovedFromTaskType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_UsersRemovedFromTaskType.ProtoReflect.Descriptor instead.
func (*SystemMessage_UsersRemovedFromTaskType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 10}
}

func (x *SystemMessage_UsersRemovedFromTaskType) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SystemMessage_TaskStatusChangedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewStatusId uint32 `protobuf:"varint,1,opt,name=new_status_id,json=newStatusId,proto3" json:"new_status_id,omitempty"`
}

func (x *SystemMessage_TaskStatusChangedType) Reset() {
	*x = SystemMessage_TaskStatusChangedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_TaskStatusChangedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_TaskStatusChangedType) ProtoMessage() {}

func (x *SystemMessage_TaskStatusChangedType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_TaskStatusChangedType.ProtoReflect.Descriptor instead.
func (*SystemMessage_TaskStatusChangedType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 11}
}

func (x *SystemMessage_TaskStatusChangedType) GetNewStatusId() uint32 {
	if x != nil {
		return x.NewStatusId
	}
	return 0
}

type SystemMessage_WelcomeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SystemMessage_WelcomeType) Reset() {
	*x = SystemMessage_WelcomeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tsystem_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage_WelcomeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage_WelcomeType) ProtoMessage() {}

func (x *SystemMessage_WelcomeType) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tsystem_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage_WelcomeType.ProtoReflect.Descriptor instead.
func (*SystemMessage_WelcomeType) Descriptor() ([]byte, []int) {
	return file_teatypes_tsystem_messages_proto_rawDescGZIP(), []int{0, 12}
}

func (x *SystemMessage_WelcomeType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_teatypes_tsystem_messages_proto protoreflect.FileDescriptor

var file_teatypes_tsystem_messages_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x16, 0x74, 0x65, 0x61,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x0f, 0x0a, 0x0d, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x05,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65,
	0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x65, 0x61, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x65, 0x61,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x4f, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x65,
	0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x64, 0x12, 0x5c, 0x0a, 0x12, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x63, 0x6f, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x63, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x48,
	0x00, 0x52, 0x10, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x63, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x64, 0x12, 0x60, 0x0a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x41, 0x64, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x11, 0x75, 0x73, 0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64, 0x54, 0x6f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x6c, 0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x72, 0x6f,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x15, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x4c, 0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x61, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x4c, 0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x12,
	0x6e, 0x0a, 0x18, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x32, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x16, 0x74, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12,
	0x5d, 0x0a, 0x13, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x74,
	0x6f, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x74,
	0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x54, 0x6f, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x10, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x69,
	0x0a, 0x17, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x48, 0x00, 0x52, 0x14, 0x75, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x5f, 0x0a, 0x13, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x11, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x77, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x65,
	0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x65, 0x78, 0x74,
	0x1a, 0x26, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x28, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x1a, 0x2f, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x1a, 0x41, 0x0a, 0x14, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x63, 0x6f, 0x6e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x6e,
	0x65, 0x77, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x07, 0x6e,
	0x65, 0x77, 0x49, 0x63, 0x6f, 0x6e, 0x1a, 0x3d, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41,
	0x64, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x24, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x41, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x49, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x2e, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x1a, 0x45, 0x0a, 0x1a, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x65, 0x77, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x14, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x40, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x73, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x3b, 0x0a, 0x15, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x1a, 0x21, 0x0a, 0x0b, 0x57, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teatypes_tsystem_messages_proto_rawDescOnce sync.Once
	file_teatypes_tsystem_messages_proto_rawDescData = file_teatypes_tsystem_messages_proto_rawDesc
)

func file_teatypes_tsystem_messages_proto_rawDescGZIP() []byte {
	file_teatypes_tsystem_messages_proto_rawDescOnce.Do(func() {
		file_teatypes_tsystem_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_teatypes_tsystem_messages_proto_rawDescData)
	})
	return file_teatypes_tsystem_messages_proto_rawDescData
}

var file_teatypes_tsystem_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_teatypes_tsystem_messages_proto_goTypes = []interface{}{
	(*SystemMessage)(nil),                            // 0: teatypes.SystemMessage
	(*SystemMessage_ErrorMessageType)(nil),           // 1: teatypes.SystemMessage.ErrorMessageType
	(*SystemMessage_GroupCreatedType)(nil),           // 2: teatypes.SystemMessage.GroupCreatedType
	(*SystemMessage_GroupRenamedType)(nil),           // 3: teatypes.SystemMessage.GroupRenamedType
	(*SystemMessage_GroupIconChangedType)(nil),       // 4: teatypes.SystemMessage.GroupIconChangedType
	(*SystemMessage_UsersAddedToGroupType)(nil),      // 5: teatypes.SystemMessage.UsersAddedToGroupType
	(*SystemMessage_UsersRemovedFromGroupType)(nil),  // 6: teatypes.SystemMessage.UsersRemovedFromGroupType
	(*SystemMessage_TaskCreatedType)(nil),            // 7: teatypes.SystemMessage.TaskCreatedType
	(*SystemMessage_TaskRenamedType)(nil),            // 8: teatypes.SystemMessage.TaskRenamedType
	(*SystemMessage_TaskDescriptionChangedType)(nil), // 9: teatypes.SystemMessage.TaskDescriptionChangedType
	(*SystemMessage_UsersAddedToTaskType)(nil),       // 10: teatypes.SystemMessage.UsersAddedToTaskType
	(*SystemMessage_UsersRemovedFromTaskType)(nil),   // 11: teatypes.SystemMessage.UsersRemovedFromTaskType
	(*SystemMessage_TaskStatusChangedType)(nil),      // 12: teatypes.SystemMessage.TaskStatusChangedType
	(*SystemMessage_WelcomeType)(nil),                // 13: teatypes.SystemMessage.WelcomeType
	(*User)(nil),                                     // 14: teatypes.User
	(*Icon)(nil),                                     // 15: teatypes.Icon
}
var file_teatypes_tsystem_messages_proto_depIdxs = []int32{
	14, // 0: teatypes.SystemMessage.actor:type_name -> teatypes.User
	1,  // 1: teatypes.SystemMessage.error_message:type_name -> teatypes.SystemMessage.ErrorMessageType
	2,  // 2: teatypes.SystemMessage.group_created:type_name -> teatypes.SystemMessage.GroupCreatedType
	3,  // 3: teatypes.SystemMessage.group_renamed:type_name -> teatypes.SystemMessage.GroupRenamedType
	4,  // 4: teatypes.SystemMessage.group_icon_changed:type_name -> teatypes.SystemMessage.GroupIconChangedType
	5,  // 5: teatypes.SystemMessage.users_added_to_group:type_name -> teatypes.SystemMessage.UsersAddedToGroupType
	6,  // 6: teatypes.SystemMessage.users_removed_from_group:type_name -> teatypes.SystemMessage.UsersRemovedFromGroupType
	7,  // 7: teatypes.SystemMessage.task_created:type_name -> teatypes.SystemMessage.TaskCreatedType
	8,  // 8: teatypes.SystemMessage.task_renamed:type_name -> teatypes.SystemMessage.TaskRenamedType
	9,  // 9: teatypes.SystemMessage.task_description_changed:type_name -> teatypes.SystemMessage.TaskDescriptionChangedType
	10, // 10: teatypes.SystemMessage.users_added_to_task:type_name -> teatypes.SystemMessage.UsersAddedToTaskType
	11, // 11: teatypes.SystemMessage.users_removed_from_task:type_name -> teatypes.SystemMessage.UsersRemovedFromTaskType
	12, // 12: teatypes.SystemMessage.task_status_changed:type_name -> teatypes.SystemMessage.TaskStatusChangedType
	13, // 13: teatypes.SystemMessage.welcome:type_name -> teatypes.SystemMessage.WelcomeType
	15, // 14: teatypes.SystemMessage.GroupIconChangedType.new_icon:type_name -> teatypes.Icon
	14, // 15: teatypes.SystemMessage.UsersAddedToGroupType.users:type_name -> teatypes.User
	14, // 16: teatypes.SystemMessage.UsersRemovedFromGroupType.users:type_name -> teatypes.User
	14, // 17: teatypes.SystemMessage.UsersAddedToTaskType.users:type_name -> teatypes.User
	14, // 18: teatypes.SystemMessage.UsersRemovedFromTaskType.users:type_name -> teatypes.User
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_teatypes_tsystem_messages_proto_init() }
func file_teatypes_tsystem_messages_proto_init() {
	if File_teatypes_tsystem_messages_proto != nil {
		return
	}
	file_teatypes_timages_proto_init()
	file_teatypes_tusers_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_teatypes_tsystem_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_ErrorMessageType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_GroupCreatedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_GroupRenamedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_GroupIconChangedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_UsersAddedToGroupType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_UsersRemovedFromGroupType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_TaskCreatedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_TaskRenamedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_TaskDescriptionChangedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_UsersAddedToTaskType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_UsersRemovedFromTaskType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_TaskStatusChangedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teatypes_tsystem_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage_WelcomeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_teatypes_tsystem_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SystemMessage_ErrorMessage)(nil),
		(*SystemMessage_GroupCreated)(nil),
		(*SystemMessage_GroupRenamed)(nil),
		(*SystemMessage_GroupIconChanged)(nil),
		(*SystemMessage_UsersAddedToGroup)(nil),
		(*SystemMessage_UsersRemovedFromGroup)(nil),
		(*SystemMessage_TaskCreated)(nil),
		(*SystemMessage_TaskRenamed)(nil),
		(*SystemMessage_TaskDescriptionChanged)(nil),
		(*SystemMessage_UsersAddedToTask)(nil),
		(*SystemMessage_UsersRemovedFromTask)(nil),
		(*SystemMessage_TaskStatusChanged)(nil),
		(*SystemMessage_Welcome)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teatypes_tsystem_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teatypes_tsystem_messages_proto_goTypes,
		DependencyIndexes: file_teatypes_tsystem_messages_proto_depIdxs,
		MessageInfos:      file_teatypes_tsystem_messages_proto_msgTypes,
	}.Build()
	File_teatypes_tsystem_messages_proto = out.File
	file_teatypes_tsystem_messages_proto_rawDesc = nil
	file_teatypes_tsystem_messages_proto_goTypes = nil
	file_teatypes_tsystem_messages_proto_depIdxs = nil
}
