// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: teatypes/tuploads.proto

package teaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadType int32

const (
	UploadType_UT_FILE  UploadType = 0
	UploadType_UT_IMAGE UploadType = 1
	UploadType_UT_VIDEO UploadType = 2
	UploadType_UT_AUDIO UploadType = 3
)

// Enum value maps for UploadType.
var (
	UploadType_name = map[int32]string{
		0: "UT_FILE",
		1: "UT_IMAGE",
		2: "UT_VIDEO",
		3: "UT_AUDIO",
	}
	UploadType_value = map[string]int32{
		"UT_FILE":  0,
		"UT_IMAGE": 1,
		"UT_VIDEO": 2,
		"UT_AUDIO": 3,
	}
)

func (x UploadType) Enum() *UploadType {
	p := new(UploadType)
	*p = x
	return p
}

func (x UploadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadType) Descriptor() protoreflect.EnumDescriptor {
	return file_teatypes_tuploads_proto_enumTypes[0].Descriptor()
}

func (UploadType) Type() protoreflect.EnumType {
	return &file_teatypes_tuploads_proto_enumTypes[0]
}

func (x UploadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadType.Descriptor instead.
func (UploadType) EnumDescriptor() ([]byte, []int) {
	return file_teatypes_tuploads_proto_rawDescGZIP(), []int{0}
}

type Upload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt    uint64     `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Url          string     `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Filename     string     `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Type         UploadType `protobuf:"varint,4,opt,name=type,proto3,enum=teatypes.UploadType" json:"type,omitempty"`
	Size         uint32     `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	LargePreview *Image     `protobuf:"bytes,6,opt,name=large_preview,json=largePreview,proto3" json:"large_preview,omitempty"`  // optional large preview: for UT_IMAGE and UT_VIDEO
	SmallPreview *Image     `protobuf:"bytes,10,opt,name=small_preview,json=smallPreview,proto3" json:"small_preview,omitempty"` // optional small square preview: for UT_IMAGE and UT_VIDEO
	Duration     uint32     `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`                             // non-zero for UT_AUDIO and UT_VIDEO
	ContentType  string     `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`     // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
}

func (x *Upload) Reset() {
	*x = Upload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teatypes_tuploads_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upload) ProtoMessage() {}

func (x *Upload) ProtoReflect() protoreflect.Message {
	mi := &file_teatypes_tuploads_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upload.ProtoReflect.Descriptor instead.
func (*Upload) Descriptor() ([]byte, []int) {
	return file_teatypes_tuploads_proto_rawDescGZIP(), []int{0}
}

func (x *Upload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Upload) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Upload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Upload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Upload) GetType() UploadType {
	if x != nil {
		return x.Type
	}
	return UploadType_UT_FILE
}

func (x *Upload) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Upload) GetLargePreview() *Image {
	if x != nil {
		return x.LargePreview
	}
	return nil
}

func (x *Upload) GetSmallPreview() *Image {
	if x != nil {
		return x.SmallPreview
	}
	return nil
}

func (x *Upload) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Upload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_teatypes_tuploads_proto protoreflect.FileDescriptor

var file_teatypes_tuploads_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x61, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x1a, 0x16, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x02, 0x0a, 0x06,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x34, 0x0a, 0x0d, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x65, 0x61, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x6c, 0x61, 0x72, 0x67, 0x65,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x34, 0x0a, 0x0d, 0x73, 0x6d, 0x61, 0x6c, 0x6c,
	0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x74, 0x65, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x0c, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x43, 0x0a, 0x0a,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x54,
	0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x54, 0x5f, 0x49, 0x4d,
	0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x54, 0x5f, 0x56, 0x49, 0x44, 0x45,
	0x4f, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x54, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10,
	0x03, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teatypes_tuploads_proto_rawDescOnce sync.Once
	file_teatypes_tuploads_proto_rawDescData = file_teatypes_tuploads_proto_rawDesc
)

func file_teatypes_tuploads_proto_rawDescGZIP() []byte {
	file_teatypes_tuploads_proto_rawDescOnce.Do(func() {
		file_teatypes_tuploads_proto_rawDescData = protoimpl.X.CompressGZIP(file_teatypes_tuploads_proto_rawDescData)
	})
	return file_teatypes_tuploads_proto_rawDescData
}

var file_teatypes_tuploads_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_teatypes_tuploads_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_teatypes_tuploads_proto_goTypes = []interface{}{
	(UploadType)(0), // 0: teatypes.UploadType
	(*Upload)(nil),  // 1: teatypes.Upload
	(*Image)(nil),   // 2: teatypes.Image
}
var file_teatypes_tuploads_proto_depIdxs = []int32{
	0, // 0: teatypes.Upload.type:type_name -> teatypes.UploadType
	2, // 1: teatypes.Upload.large_preview:type_name -> teatypes.Image
	2, // 2: teatypes.Upload.small_preview:type_name -> teatypes.Image
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_teatypes_tuploads_proto_init() }
func file_teatypes_tuploads_proto_init() {
	if File_teatypes_tuploads_proto != nil {
		return
	}
	file_teatypes_timages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_teatypes_tuploads_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Upload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teatypes_tuploads_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teatypes_tuploads_proto_goTypes,
		DependencyIndexes: file_teatypes_tuploads_proto_depIdxs,
		EnumInfos:         file_teatypes_tuploads_proto_enumTypes,
		MessageInfos:      file_teatypes_tuploads_proto_msgTypes,
	}.Build()
	File_teatypes_tuploads_proto = out.File
	file_teatypes_tuploads_proto_rawDesc = nil
	file_teatypes_tuploads_proto_goTypes = nil
	file_teatypes_tuploads_proto_depIdxs = nil
}
