name: Docs
on:
  push:
#    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git checkout gh-pages
          git pull
          git checkout -
      - run: make gh-deploy
