name: Docs
on:
  push:
#    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: git config --global push.default tracking
      - run: git pull
      - run: make gh-deploy
